---
- name: Sysctl options
  ansible.posix.sysctl:
    name: "{{ sysctl_opt.name }}"
    reload: true
    state: "{{ sysctl_opt.state | default('present') }}"
    value: "{{ sysctl_opt.value }}"
  loop: "{{ sysctl_options | default([]) }}"
  loop_control:
    loop_var: sysctl_opt


- name: Include os specific
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yaml"


- name: "Install python packages"
  ansible.builtin.pip:
    name: "{{ python_packages }}"
  when:
    - python_packages is defined


- name: Setup internal dns
  ansible.builtin.include_tasks: dns.yaml
  when:
    - dns_53 is defined
    - dns_53


- name: Add host entries
  ansible.builtin.blockinfile:
    backup: true
    block: |
      {% for host in hosts_file %}
      {{ host.ip }}{% for name in host.names %} {{ host.name }}{% endfor %}

      {% endfor %}
    group: "root"
    marker: "# {mark} Managed by Ansible"
    mode: "0644"
    owner: "root"
    path: "/etc/hosts"
    state: "present"
  when:
    - hosts_file is defined


# - name: Setup SomeoneWhoCares (https://someonewhocares.org/)
#   block:
#   when:
#     - someonewhocares is defined
