---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 1440m
  url: https://charts.jetstack.io
---
# https://github.com/smallstep/step-issuer?tab=readme-ov-file
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: smallstep
  namespace: cert-manager
spec:
  interval: 1440m
  url: https://smallstep.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: ">= v1.18.2 < v1.19.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 1m
  values:
    crds:
      enabled: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    config:
      enableGatewayAPI: true
    extraArgs:
      - --enable-gateway-api
