---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-dns
  namespace: cert-manager
spec:
  interval: 1440m
  url: https://github.com/kubernetes-sigs/external-dns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: cert-manager
spec:
  interval: 1440m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: external-dns
  path: ./kustomize
  targetNamespace: cert-manager
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/args
          value:
            - --source=service
            - --source=ingress
            # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
            # You don't need to set this flag, but if you leave it unset, you will receive warning
            # logs when ExternalDNS attempts to create TXT records.
            - --registry=noop
            # IMPORTANT: If you have records that you manage manually in Pi-hole, set
            # the policy to upsert-only so they do not get deleted.
            - --policy=upsert-only
            - --provider=pihole
            # Switch to pihole V6 API
            - --pihole-api-version=6
            # Change this to the actual address of your Pi-hole web server
            - --pihole-server=${pihole_url}
            - --pihole-tls-skip-verify
        - op: add
          path: /spec/template/spec/containers/0/envFrom
          value:
            - secretRef:
                # Change this if you gave the secret a different name
                name: pihole-password
      target:
        kind: Deployment
        name: external-dns
