---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1440m
  url: https://github.com/rancher/local-path-provisioner
  ref:
    semver: ">=v0.0.31"
