---
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvdp
  namespace: nvidia-gpu
spec:
  interval: 1440m
  url: https://nvidia.github.io/k8s-device-plugin
