---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: seerr
  namespace: yarr
spec:
  interval: 1440m
  url: oci://ghcr.io/seerr-team/seerr/seerr-chart
  ref:
    tag: 3.6.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: yarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: seerr
    namespace: yarr
  values:
    config:
      persistence:
        existingClaim: yarr-jellyseerr-config
    extraEnv:
      - name: TZ
        value: ${yarr_timezone}
    ingress:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: homelab-internal
      hosts:
        - host: ${seerr_hostname}
      ingressClassName: nginx
      tls:
        - hosts:
            - ${seerr_hostname}
          secretName: seerr-tls
    podSecurityContext:
      fsGroup: ${groupId}
    securityContext:
      capabilities:
        drop: [ "ALL" ]
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      readOnlyRootFilesystem: false
      privileged: false
      runAsUser: ${userId}
      runAsGroup: ${groupId}
