apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 1d
  url: https://charts.rook.io/release
