---
- name: "[helm] NFS - Add NFS repo"
  kubernetes.core.helm_repository:
    repo_name: "nfs-subdir-external-provisioner"
    repo_state: "present"
    repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"

- name: "[helm] NFS - Install NFS"
  kubernetes.core.helm:
    chart_ref: "nfs-subdir-external-provisioner/nfs-subdir-external-provisioner"
    create_namespace: yes
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    release_name: "nfs-subdir-external-provisioner"
    release_namespace: "storage-nfs"
    release_values:
      replicaCount: "{{ item.replicas | default(1) | int }}"
      storageClass:
        name: "nfs-client-{{ item.name }}"
        defaultClass: "{{ item.default | default(true) | bool }}"
      nfs:
        server: "{{ item.server }}"
        path: "{{ item.path }}"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: "nfs-subdir-external-provisioner"
                  release: "nfs-subdir-external-provisioner"
                  "sc-name": "nfs-client-{{ item.name }}"
              topologyKey: kubernetes.io/hostname
      labels:
        "sc-name": "nfs-client-{{ item.name }}"
    update_repo_cache: yes
    wait: yes
    wait_timeout: "15m"
  loop: "{{ k3s.config.nfs }}"