---
- name: "Create a k3s config directory"
  ansible.builtin.file:
    group: "root"
    mode: "600"
    owner: "root"
    path: "{{ config_directory_path }}"
    recurse: yes
    state: directory

- name: "[helm] Rook - Add rook repo"
  kubernetes.core.helm_repository:
    repo_name: "rook-release"
    repo_state: "present"
    repo_url: "https://charts.rook.io/release"

- name: "[helm] Rook - Install rook"
  kubernetes.core.helm:
    chart_ref: "rook-release/rook-ceph"
    create_namespace: yes
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    release_name: "rook-ceph"
    release_namespace: "rook-ceph"
    release_values:
      csi:
        provisionerTolerations:
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
        rbdProvisionerTolerations:
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
    update_repo_cache: yes
    wait: yes
    wait_timeout: "15m"

- name: "[Rook] Ceph - Generate rbac definition"
  ansible.builtin.template:
    dest: "{{ config_directory_path }}/rook-ceph-monitoring-rbac.yaml"
    src: "rook-ceph-monitoring-rbac.yaml"

- name: "[Rook] Ceph - Apply Ceph rbac"
  kubernetes.core.k8s:
    apply: yes
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: "{{ config_directory_path }}/rook-ceph-monitoring-rbac.yaml"
    state: "present"
    wait: yes

- name: "[Rook] Ceph - Generate cluster definition"
  ansible.builtin.template:
    dest: "{{ config_directory_path }}/rook-ceph-config.yaml"
    src: "rook-ceph-config.yaml"

- name: "[Rook] Ceph - Apply Ceph cluster"
  kubernetes.core.k8s:
    apply: yes
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: "{{ config_directory_path }}/rook-ceph-config.yaml"
    state: "present"
    wait: yes

- name: "[Rook] Ceph - Generate Storage Class definition"
  ansible.builtin.template:
    dest: "{{ config_directory_path }}/rook-ceph-storage-class.yaml"
    src: "rook-ceph-storage-class.yaml"

- name: "[Rook] Ceph - Apply Storage Classe"
  kubernetes.core.k8s:
    apply: yes
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: "{{ config_directory_path }}/rook-ceph-storage-class.yaml"
    state: "present"
    wait: yes
    wait_sleep: 5
    wait_timeout: 900