---
- name: "Install Bind9 related packages"
  ansible.builtin.apt:
    name:
      - bind9
      - bind9-doc

- name: "Create images directory to store image disks"
  ansible.builtin.file:
    mode: "600"
    path: "{{ bind9.config.image_disk.path | default('/root/images') }}"
    state: directory
  when: bind9.config.image_disk is defined

- name: "Create bind image disk"
  community.general.filesize:
    path: "{{ bind9.config.image_disk.path | default('/root/images') }}/bind9.bin"
    size: "{{ bind9.config.image_disk.size }}"
  when: bind9.config.image_disk is defined

- name: "Format the image disk"
  community.general.filesystem:
    dev: "{{ bind9.config.image_disk.path | default('/root/images') }}/bind9.bin"
    fstype: "ext4"
  when: bind9.config.image_disk is defined

- name: "Get Bind9 user ID"
  ansible.builtin.user:
    name: "bind"
  register: bind_user_id
  when: bind9.config.image_disk is defined

- name: "Mount /var/cache/bind"
  ansible.posix.mount:
    dump: "0"
    fstype: "ext4"
    opts: "loop"
    passno: "0"
    path: "/var/cache/bind"
    src: "{{ bind9.config.image_disk.path | default('/root/images') }}/bind9.bin"
    state: "mounted"
  when: bind9.config.image_disk is defined

- name: "Change owner to bind"
  ansible.builtin.file:
    owner: "bind"
    path: "/var/cache/bind"
    recurse: yes
    state: "directory"
  when: bind9.config.image_disk is defined

- name: "Generate bind9 files"
  ansible.builtin.template:
    dest: "/etc/bind/{{ item }}"
    mode: "644"
    src: "{{ item  }}"
  loop:
    - "named.conf"
    - "named.conf.local"
    - "named.conf.log"
    - "named.conf.options"

- name: "Generate zone files"
  ansible.builtin.include_tasks: "zones.yaml"
  loop: "{{ bind9.zones }}"
  loop_control:
    loop_var: "zone"

- name: "Restart Bind9"
  ansible.builtin.service:
    name: "bind9.service"
    state: "restarted"