---
- name: "Check if file exists"
  ansible.builtin.stat:
    path: "/var/lib/bind/db.{% if zone.file_name is defined %}{{ zone.file_name }}{% else %}{{ zone.name }}{% endif %}"
  register: file_exists

- name: "Get zone file serial"
  ansible.builtin.shell: "set -o pipefail %% cat /var/lib/bind/db.{% if zone.file_name is defined %}{{ zone.file_name }}{% else %}{{ zone.name }}{% endif %} | grep Serial | awk '{print $1}'"
  register: serial
  when: file_exists.stat.exists

- name: "Update zone file"
  ansible.builtin.template:
    dest: "/var/lib/bind/db.{% if zone.file_name is defined %}{{ zone.file_name }}{% else %}{{ zone.name }}{% endif %}"
    mode: "644"
    src: "db"
  when:
    - file_exists.stat.exists
    - serial is defined

- name: "Generate zone file"
  ansible.builtin.template:
    dest: "/var/lib/bind/db.{% if zone.file_name is defined %}{{ zone.file_name }}{% else %}{{ zone.name }}{% endif %}"
    mode: "644"
    src: "db"
  when:
    - not file_exists.stat.exists