---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: 'templates/'
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ['--allow-multiple-documents']
        files: '.pre-commit-config.yaml'
        exclude: 'templates/'
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
  # TODO: find a fix. It keeps asking me that it cannot find the jmespath which
  # is installed and working with the ansible-lint command line. Already tried
  # many things without success. Will check that later.
  # - repo: https://github.com/ansible-community/ansible-lint.git
  #   rev: v25.1.3
  #   hooks:
  #     - id: ansible-lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args: ["--fix"]
