apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  # dependsOn:
  #   - name: kube-prometheus-stack
  #     namespace: monitoring
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: ">= v1.18.2 < v1.19.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 1m
  values:
    crds:
      enabled: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    config:
      enableGatewayAPI: true
    extraArgs:
      - --enable-gateway-api
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-certificates
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  interval: 30m
  chart:
    spec:
      chart: step-certificates
      version: ">= 1.28.4 < v1.29.0"
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: cert-manager
      interval: 1m
