---
base:
  vlan:
    enabled: true
    vlans_definition: |
      auto eth0.30
      iface eth0.30 inet dhcp
        vlan-raw-device eth0
idh:
  timezone: "{{ local_timezone }}"
  hostname: ca
  root_ssh_pubkey: "{{ admin_ssh_pub_key }}"
  default_password: "{{ admin_password }}"
packages_list:
  # yubikey pkg
  - yubikey-manager
  - pcscd
  # needed to build infinite noise trng
  - libftdi-dev
  - libusb-dev
  - make
  - git
  - gcc
  # needed to build step-ca with yubikey support
  # (see: https://github.com/smallstep/certificates/blob/master/CONTRIBUTING.md#build-step-ca-using-cgo)
  - libpcsclite-dev
  - pkg-config
go_lang_checksum: sha256:9aaeb044bf8dbf50ca2fbf0edc5ebc98b90d5bda8c6b2911526df76f61232919
certificate_authority_server_temporary_folder_path: "/home/{{ ansible_user }}/cas"
cas:
  trng:
    enabled: true
  mount:
    path: /mnt
    src: LABEL=key
  root_ca:
    name: homelab
    dns: "{{ cas_root_ca_dns }}"
    provisioner: "{{ cas_root_ca_provisioner }}"
  yubikey:
    enabled: true
    product_id: 407
    root:
      slot: "{{ cas_yubikey.root_slot }}"
    intermediate:
      name: home
      slot: "{{ cas_yubikey.intermediate_slot }}"
  config:
    authority:
      claims:
        # 1 months
        maxTLSCertDuration: 720h
      # policy:
      #   x509:
      #     allow:
      #       dns:
      #         - "*.example.com"
