---
all:
  hosts:
    nameserver_old:

    nameserver:
  vars:
      timezone: "UTC"

      tmp_size: "512M"
      dns_53: "{{ network.nameservers.block_malware[0] }}"

      hosts_file:
        - ip: "127.0.0.1"
          names:
            - "nameserver"
            - "ns1.nameserver.com"

      sshd_config:
        port: 2222
        permit_root_login: "yes"
        password_authentication: "no"
        x11_forwarding: "no"

      logrotate:
        - name: "ansible_default"
          log_path:
            - "/var/log/alternatives.log"
            - "/var/log/auth.log"
            - "/var/log/syslog"
          options:
            - "compress"
            - "delaycompress"
            - "create 644"
            - "daily"
            - "missingok"
            - "rotate 30"
            - "size 500M"
            - "notifempty"
            - "copytruncate"
            - "dateext"

      fail2ban_config:
        ignore_ip:
          - "127.0.0.1/32"
          - "::1"
          - "{{ ansible_default_ipv4.address }}"
        bantime: "31536000" # 60*60*24*365 (1 year)
        findtime: "3600" # 1 hour
        maxretry: "2"
        jails:
          - name: "sshd"
            port: "2222"
            logpath: "%(sshd_log)s"
            backend: "%(sshd_backend)s"
            options:
              mode: "aggressive"

      ufw_ipv6: "no"
      ufw_default_input_policy: DROP
      ufw_default_output_policy: ACCEPT
      ufw_default_forward_policy: ACCEPT
      ufw_default_application_policy: ACCEPT
      ufw_logging: "off"
      ufw_state: "enabled"

      ufw_rules:
        - comment: "Allow NTP sync"
          to_port: "123"
          direction: "out"
          proto: "udp"
          rule: "allow"

        - comment: "Allow ssh stall"
          to_port: "22"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow real ssh"
          to_port: "2222"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow dns udp"
          to_port: "53"
          direction: "in"
          proto: "udp"
          rule: "allow"

        - comment: "Allow dns tcp"
          to_port: "53"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow http"
          to_port: "80"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow https"
          to_port: "443"
          direction: "in"
          proto: "tcp"
          rule: "allow"

      bind9:
        zones:
          - type: "master"
            name: "acme.com"
            email: "hostmaster@acme.com"
            name_servers:
              - "ns1.acme.com"
              - "ns1.google.com"
            hosts:
              - name: "ns1"
                type: "A"
                content: "123.456.789.012"
              - name: "@"
                type: "A"
                content: "{{ ansible_host }}"
              - name: "@"
                type: "MX"
                content: "10 mail.acme.com."
              - name: "mail"
                type: "A"
                content: "123.456.789.012"

      certificates:
        ca:
          curve: "secp256r1"
          name: "nameserver"
          size: 4096
          # X25519 is not supported rigth now by the module
          # type: "X25519"
          type: "RSA"
        config:
          owner: "root"
          group: "root"
          private_key:
            curve: "secp256r1"
            size: 4096
            # X25519 is not supported rigth now by the module
            # type: "X25519"
            type: "RSA"
          path: "/etc/nginx/certs"
          country_name: "CA"
          organization_name: "nameserver"
          organizational_unit_name: "HM"
          state_or_province_name: "QC"
        certs:
          - name: "localhost"
            common_name: "localhost"
            subject_alt_name: "DNS:localhost"