---
home:
  hosts:
    print:
      user_data:
        users:
          - name: print
            primary_group: print
            shell: "/bin/bash"
            sudo: "ALL=(ALL) NOPASSWD:ALL"
            groups:
              - users
              - adm
              - netdev
            ssh_keys:
              - "{{ ssh_key }}"
        pkg_update: yes
        pkg_upgrade: yes
      network_config:
        ethernet:
          dhcp4: yes
        wifi:
          dhcp4: no
          addresses:
            - "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('host') }}"
          gateway4: "{{ network.zones.home.lans.lab.gateway }}"
          nameservers: "{{ network.nameservers.block_malware_porn }}"
          ssid: "{{ network.zones.home.lans.lab.wifi.wifi_name }}"
          password: "{{ network.zones.home.lans.lab.wifi.wifi_password }}"

      hosts_file:
        - ip: "127.0.0.1"
          names:
            - "print.lan"

      sshd_config:
        permit_root_login: "no"
        password_authentication: "no"
        x11_forwarding: "no"


      fail2ban_config:
        ignore_ip: "{{ fail2ban_config_template.ignore_ip }}"
        bantime: "{{ fail2ban_config_template.bantime }}"
        findtime: "{{ fail2ban_config_template.findtime }}"
        maxretry: "{{ fail2ban_config_template.maxretry }}"
        jails:
          - name: "sshd"
            port: "ssh"
            logpath: "%(sshd_log)s"
            backend: "%(sshd_backend)s"
            options:
              mode: "normal"


      ufw_ipv6: "no"
      ufw_default_input_policy: DROP
      ufw_default_output_policy: ACCEPT
      ufw_default_forward_policy: DROP
      ufw_default_application_policy: SKIP
      ufw_logging: "off"
      ufw_state: "enabled"

      ufw_rules:
        - comment: "Allow NTP sync"
          to_port: "123"
          direction: "out"
          proto: "udp"
          rule: "allow"

        - comment: "Allow ssh from Lab"
          from_ip: "{{ network.zones.home.lans.lab.cidr }}"
          to_port: "22"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow Cups from main"
          from_ip: "{{ network.zones.home.lans.main.cidr }}"
          to_port: "631"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow Cups from work"
          from_ip: "{{ network.zones.home.lans.work.cidr }}"
          to_port: "631"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow Cups from lab"
          from_ip: "{{ network.zones.home.lans.lab.cidr }}"
          to_port: "631"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow multicast DNS (mDNS) with bonjour from main"
          from_ip: "{{ network.zones.home.lans.main.cidr }}"
          to_port: "5353"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          direction: "in"
          proto: "udp"
          rule: "allow"

        - comment: "Allow multicast DNS (mDNS) with bonjour to main"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "5353"
          to_ip: "{{ network.zones.home.lans.main.cidr }}"
          direction: "out"
          proto: "udp"
          rule: "allow"

        - comment: "Allow multicast DNS (mDNS) with bonjour from work"
          from_ip: "{{ network.zones.home.lans.work.cidr }}"
          to_port: "5353"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          direction: "in"
          proto: "udp"
          rule: "allow"

        - comment: "Allow multicast DNS (mDNS) with bonjour to work"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "5353"
          to_ip: "{{ network.zones.home.lans.work.cidr }}"
          direction: "out"
          proto: "udp"
          rule: "allow"

        - comment: "Allow multicast DNS (mDNS) with bonjour from lab"
          from_ip: "{{ network.zones.home.lans.lab.cidr }}"
          to_port: "5353"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          direction: "in"
          proto: "udp"
          rule: "allow"

        - comment: "Allow multicast DNS (mDNS) with bonjour to lab"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "5353"
          to_ip: "{{ network.zones.home.lans.lab.cidr }}"
          direction: "out"
          proto: "udp"
          rule: "allow"

        - comment: "Allow SMB 137 from main"
          from_ip: "{{ network.zones.home.lans.main.cidr }}"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          to_port: "137"
          direction: "in"
          proto: "udp"
          rule: "allow"

        - comment: "Allow SMB 137 to main"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "137"
          to_ip: "{{ network.zones.home.lans.main.cidr }}"
          direction: "out"
          proto: "udp"
          rule: "allow"

        - comment: "Allow SMB 137 from work"
          from_ip: "{{ network.zones.home.lans.work.cidr }}"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          to_port: "137"
          direction: "in"
          proto: "udp"
          rule: "allow"

        - comment: "Allow SMB 137 to work"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "137"
          to_ip: "{{ network.zones.home.lans.work.cidr }}"
          direction: "out"
          proto: "udp"
          rule: "allow"

        - comment: "Allow SMB 137 from lab"
          from_ip: "{{ network.zones.home.lans.lab.cidr }}"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          to_port: "137"
          direction: "in"
          proto: "udp"
          rule: "allow"

        - comment: "Allow SMB 137 to lab"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "137"
          to_ip: "{{ network.zones.home.lans.lab.cidr }}"
          direction: "out"
          proto: "udp"
          rule: "allow"

        - comment: "Allow SMB 139 from main"
          from_ip: "{{ network.zones.home.lans.main.cidr }}"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          to_port: "139"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 139 to main"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "139"
          to_ip: "{{ network.zones.home.lans.main.cidr }}"
          direction: "out"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 139 from work"
          from_ip: "{{ network.zones.home.lans.work.cidr }}"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          to_port: "139"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 139 to work"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "139"
          to_ip: "{{ network.zones.home.lans.work.cidr }}"
          direction: "out"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 139 from lab"
          from_ip: "{{ network.zones.home.lans.lab.cidr }}"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          to_port: "139"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 139 to lab"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "139"
          to_ip: "{{ network.zones.home.lans.lab.cidr }}"
          direction: "out"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 445 from main"
          from_ip: "{{ network.zones.home.lans.main.cidr }}"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          to_port: "445"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 445 to main"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "445"
          to_ip: "{{ network.zones.home.lans.main.cidr }}"
          direction: "out"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 445 from work"
          from_ip: "{{ network.zones.home.lans.work.cidr }}"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          to_port: "445"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 445 to work"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "445"
          to_ip: "{{ network.zones.home.lans.work.cidr }}"
          direction: "out"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 445 from lab"
          from_ip: "{{ network.zones.home.lans.lab.cidr }}"
          to_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          to_port: "445"
          direction: "in"
          proto: "tcp"
          rule: "allow"

        - comment: "Allow SMB 445 to lab"
          from_ip: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}/32"
          from_port: "445"
          to_ip: "{{ network.zones.home.lans.lab.cidr }}"
          direction: "out"
          proto: "tcp"
          rule: "allow"

      cups:
        domain_name: "lan"

        user: "cups"
        password: "cups"
        ip_listen: "0.0.0.0"
        ip_list_range:
          - "{{ network.zones.home.lans.main.cidr }}"
          - "{{ network.zones.home.lans.work.cidr }}"
          - "{{ network.zones.home.lans.lab.cidr }}"
        ip_admin:
          - "{{ network.zones.home.lans.lab.cidr }}"