apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-issuers-secret-values
  namespace: flux-system
stringData:
  url: ENC[AES256_GCM,data:uK0pvj8+9pocEnpSH/oZd0Op7pkD/q4a8q3V2hUqxUE=,iv:u/xvibSG0iuUxUsqIZmYoRye44E6P3sy0dUQVWMCyBo=,tag:0xxaCitt0rr6spBY6Tc3TQ==,type:str]
  caBundle: ENC[AES256_GCM,data:CS7eu0kARTM+SkYwNR7+9KzdBlU3vUpItTbV4973+NhWf+8Up5aJINiK43h07DhRKCXnQqzpr698cweKk138aGOjA+/R19+PqzEKf8gzvl7WfFtdE0cTbJ5Gm71eG3SdYzKYV64i+o2ja6K1TJgw4ZEbBo3dKqIuiWpaiCWLYAKHuxDYBjRlcqziBhI4XW6OKwtIlaOfTJbKtfHCY2EE1ihJC7egkAuzDxRVBybH5Upa4Nbz41Mdi+KR0XjMfI5nHqchyN+a51OyODHbq7u2mlAMNn2nIz+lPOh6g3k6Wa1upQAjGirVM6kkRXRD9Cat6i5rhNG5xTca9nyc0fFafloawtvaZkQq6fZsR25KTC5646QPbbbDzP+1GQ1eg/5FOFAbQdfOHqqXv4OWSgy4pUVJTY80ii8p+NYJhi1ljlHpgz+2sOSJ2WxtiAVtJ+svXxgnQK62Sa3JinhbEOpTtqo4jRomRP+QyhiFgLKPRWrS1EA1b5OuDu4whmemXGGAdRt5ue3Qx2WzbxRLXyFW4jfsVXOyCDc++MdxDNlRppnJKNcWUchvNLvZWmfhbVeYEvfq/2L9tXOK74NU3rSCYAcIZ9kQxZnNjLy2GPulAD69mFoM98PWtjNo466SDIvhNi6ORODg4i4Yg15RXL7ULSWQWL/8HCOHOVDUHmIlRVh8Z0d5ekWqfaKjRO4+mJY19dFQzxQFR2uU3TCPZGjmYRVDl5AwQn/fRzOBLa+6keZyYUhPDqiIqSlY9b/bBk1eDqCNctgpww6KYrjrvm7Qi60jtz+GHyVjc9UG1Y771y4gsAPzGNtkYbvMJH3+bkPXOwxRBMzrqMlVQmcWU668dDuXqGlCOI1hM1Wpq0fcWR/Q8I3oyjdHnjBJRDaGUjZDMjNVFFGGakjiyTeCNbAi7U5kXj6Wk0KezfptkNdMlyG5VwmRKak31ninTgrR+SNAMXMHhLvhf1ciH1DW7BFjr5KDmsHfdbOEUeHSwgA0sUKAOru8fQWzAsozTMptHzsRq+N4HUE+B384jbo7RWiwwlFP9wqChl6idZpk5YjfOAQGdXdHZp+UWmdNELQpU8WFBIGvxHTUWwE=,iv:Fys1bAR9GKRYFm2sHNLneR7/YltDi3Cww6Bfu+hghxk=,tag:/36262IObXHheJghwjdVkw==,type:str]
  email: ENC[AES256_GCM,data:gk59dqwunEsE23F0M7E=,iv:o8vLVC3CdCmTIkPlrHLkciF+RNXlyWirjgoMfq7bGAk=,tag:1a67G51dBViXrZgRWFECqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RzV5UkF1alBHOEVkdGRj
        ckQ5YnRnSmN4QVNQWVMwdTI2c3ZxU3RoZkU0CjdQdXpuQ2I2bjRsdlRYNjBFVDAx
        b3FCM2tNbFVNbnpoVlRyNDZJYkI2Zk0KLS0tIGM4SVRSTnVJa04xa21HMWtLN3Jh
        WjNrUTRhUGhtbFB4UHltb3U2QVgvaTQKz/44NAoT6XwCsuEzv6uveK8WZHs5bYbY
        Yi/LUM+WuPy2kBU+RDRIw4Osec8FFD9piG8zMUYtJRcEi4OmB0q+Pg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T22:44:20Z"
  mac: ENC[AES256_GCM,data:3iLNT8R1dlUvz+GCzjbXMsHCUO2gUuInZEdwANiCusF8gqncHIawxwRktRULZCrjb2VC0BsFLb1KydpCY3ZzlNw4muz9qGRPmCnnS9Olx5u0GsKNci0jEHYHQzFodPeLdAWTPKYyeMHn1maFUFkWxnkSw5fu9P+8E7hMY2eGxCY=,iv:bBje7VT6r+PfMrl9TQXtoZzKAE0spY6br9sD5XSef94=,tag:glZQPKaKtvV360cXn+cQnQ==,type:str]
  version: 3.13.1
