apiVersion: v1
kind: Secret
metadata:
  name: cilium-values
  namespace: flux-system
stringData:
  ipv4_k8s00_router: ENC[AES256_GCM,data:EJ357XkTIfQg/t2P,iv:Y0GvsO04jd/AdIX9KcC1DvqopdK/TtG7FMDSJeTNsFw=,tag:sMvb0PPjYUQtfws11U73rA==,type:str]
  ipv4_mgmt_bgp_cidr: ENC[AES256_GCM,data:MSQPlXl7IR3LvmKBEvY=,iv:sVerFdcmc9iiMH3QiXulo4+2CozVpVRkq00q6SQlupg=,tag:EhYx+nS3hnkpjQzPywgr/w==,type:str]
  ipv4_service_bgp_cidr: ENC[AES256_GCM,data:yRfsgwJPDSlIQvme/L6Z,iv:1IQDzTdwMYzfM2ANHxt9aj12oia2zLOsITWJnyyq43U=,tag:Z/ulnRDD/LGL0JbffCgAMQ==,type:str]
  ipv4_k8s00_bgp_cidr: ENC[AES256_GCM,data:pGqqAA+CKy5QxC4pmvu5,iv:GbJCRfOBbw8Setp7BBKeGq7Onk5cbd0oFLh4+BmBPa0=,tag:D7g6/cSDMLB442GEFy9ymw==,type:str]
  ipv4_service_service_bgp_cidr: ENC[AES256_GCM,data:3ZTJYPSCLb9F6usX3vrY,iv:/ReXFlUNvepYAKTy0fYKnobnQcFga3spbCTd4rIMGko=,tag:4sqQ0/UTUpOm4dKLUzkWFA==,type:str]
  ipv4_casa_bgp_cidr: ENC[AES256_GCM,data:eecWxOXgwVmT0WCJTqjT,iv:ZQ//mHvUs7TtiPW4X97SahFGCWtvmaWzyvd2PXAY4HI=,tag:/nogg6XNpJTSKNrROgFe7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNzRmdDVNTDg5OTNiVnhL
        T2pma0F1bXZOWFk1cS84dVVrUmg2Q3k4M0FZCmZSV0lFeFpOUFZEaHRXYkZHb1ZJ
        TTN6dHJNYi9BTXpuNDZ4OWxlMWY2YXMKLS0tIG5xUUpyNGpDUjkwN2VUN1dYZ0ha
        Nkpwc1I3UnVIdWxtQ3plUTZzQU9qZU0KyXhvx3QvjJKSaKTOaIBqqovhMsNGAk25
        S5u8K4kB5tosISqh9Tm2PCwRCQvDFfCiaQ3Pktl0keploPSdwgNkvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T20:45:36Z"
  mac: ENC[AES256_GCM,data:lt59sMT+3I6XgF2aef4HjEIFdzOVzBP3Cbw/xcDVwAGLKEh/tHcnI+aRDAaytdGCwUovvuPlRGJasE8eIf0vGccwPH89mDWuLE/EgGGCqfNkykBiwcdnu+UK9HYWVip4LcL+OUuGAqW4j4tlDc5+ZvrbRAvrBOnOW4/8SFyLMqM=,iv:MG7tj4eR6o1nwVGcGYON0OX83WdiS23xmXC9OUbSQiA=,tag:gRUTANmXSotpMKhDTbtbgg==,type:str]
  version: 3.13.1
