apiVersion: v1
kind: Secret
metadata:
  name: pihole-password
  namespace: cert-manager
stringData:
  EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:7DM3P4cxyq2s/ldrELra,iv:saNoYyxHNRVPl+7A1YaHLuZJZ1/gGjYGcxnIke1sHSE=,tag:p1E1WH6kFThT98u38QX6Jw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcnhJWm5IeHRCWGRwdmto
        R1BDVTAzb09Cemc3bkVpS3JTaHFMYVB4N2pNCk9vaENGbDU0eWZLUnp6T2ZJb1R5
        Z0kxWGF3NW0ra0FZZnNlK0p6MUo2QzAKLS0tIFhaRXY0c2pJSThadkVSWld1RmNF
        YndiSjVITXFKU1ZoeUd0SkkxdS8rd28KkRTHB132gyIB83DDuXHhqxtsNdS1Tml4
        pVl96GeN0j6WcJ3iz4X9sdxYwPnVPDE7uToVbyz7gAXWBdVMp1/AqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-25T16:15:05Z"
  mac: ENC[AES256_GCM,data:Pm309dJMY4bigWJNSd/UGbJllWzx2IwaUORT0aWuQWQ34YpqTPYvPFbnEbagWgr1u+jyfpExs8JqIjZAELeECT1aHoUtAl42w35KU576L2OI9iTKRPfS+D5Yy6xT7yjsij8u4Se3LH9mEl7R3O7t8HzpLjRMvh19qiRV9NkGSl0=,iv:qn8sFMXLdqKjRuNmEE6U+EyHO+yYimCZaQriK+IvKHI=,tag:qRs5NM9Pm1AvmquJ8LTPaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
