apiVersion: v1
kind: Secret
metadata:
  name: global-variables
  namespace: flux-system
stringData:
  routerIpMgmt: ENC[AES256_GCM,data:f8mGDDt690x4gjg=,iv:BdBfVIPGE72v/ZmBE4+LrtWCqPY4vVHmCcGGUbPBt/Q=,tag:XRjsaH/rR5FjZFC/ZQ6EoQ==,type:str]
  routerIpService: ENC[AES256_GCM,data:tz3ZQoCR1rSpRYXI,iv:gxAarmWibolhhSodd9j7Thrcg3WmKyIvVl2FMHoxIB8=,tag:LYleRKzc595cyQVgetri3w==,type:str]
  nasIp: ENC[AES256_GCM,data:VuWOIAMcrEx5+t8Pjg==,iv:+p34XqVQAdoTe1mRJvdmnZDcQNvhmqUzHdbJgE6TyXs=,tag:VqdLWXm2mnnA0F/2LEpKRg==,type:str]
  nasIpmgmt: ENC[AES256_GCM,data:0gGpp1iNx0bs4ZyE,iv:4b/Rgl6OkcT/Gg/r5vYQnqotFc4aCVvU+cpqg5D6uL4=,tag:igIPSAmxZY29QP+XPIHlGw==,type:str]
  nasNfsPath: ENC[AES256_GCM,data:pO+GlccozO8=,iv:fwszXZWuLvISUD4dJlmLTodiNpCyGRNRtnSUsJ5oJqY=,tag:OMXE2jMrNPAWO+5o3NecYQ==,type:str]
  userId: ENC[AES256_GCM,data:ZmXon14=,iv:3ESrO1TGZfQSoOf0UJpDMpjyKpVqtizbxbQsOquTDNE=,tag:v18gjcAjOE+Ms6SapImXSQ==,type:str]
  groupId: ENC[AES256_GCM,data:MO0HNIc=,iv:74WMzmcmKbY596xNddBGcGBATVfOfnONq3g/+SXIyNY=,tag:SBGSvHX19vYLL1UsQIV3gA==,type:str]
  timezone: ENC[AES256_GCM,data:9PpxXQ/5U0uhojKp3xji,iv:7ZZVS7RzvqdVzHqyS2oQDFrpCBgeBP5RMf5ql0I6XUY=,tag:+YvhN374i0r/P5i4GEd5CA==,type:str]
  mainDomain: ENC[AES256_GCM,data:5M5rEKMzCA==,iv:z7U3EnhoIJwHhOArea4HBG2etxXZoZsOY4bwIIAGQGE=,tag:dLQCu9Cc/bmBlGnA7Xzq5A==,type:str]
  mainDomainOld: ENC[AES256_GCM,data:1Z/NvKjyIP8=,iv:Aoz1bndTHDDzEk6qPfbYa34DurveQWzCL4kzV1fNFjg=,tag:s33IUDaNQhfBatQVAmNz+Q==,type:str]
  homeDomainOld: ENC[AES256_GCM,data:DpQCTAYOKicV4TMc1w==,iv:i2iP78fVeKPjWhEBksDv7wBvfU64w0WBpf/Zfb2Q40w=,tag:qqH+ZlZU0bOtnCqbFXd7Hg==,type:str]
  homeDomain: ENC[AES256_GCM,data:YMJ7/MYuCURqbbS0,iv:vXaDONAPZ4FHcJhcGymyfIBmBHI72vGApoNyz16OtrU=,tag:F5ojG43AZudvSGiPfTr3bw==,type:str]
  mgmtDomainOld: ENC[AES256_GCM,data:5PrKim/Y7EH9ZXW7cUUyx8be,iv:HdeaCFgE7TZ90FCopg6rpuFZw6BENSCbfWktMOXO8zk=,tag:5GRZxaPopEROz0ejzz7DUQ==,type:str]
  mgmtDomain: ENC[AES256_GCM,data:6GsD/v4fSTmcfnFJQZJPj5U=,iv:0noG6TtzfgyetizWIJbywBEDm24g5N0jTANazyDzb4k=,tag:zgaYcJqSG3LN7tnJ5wqa7A==,type:str]
  serviceDomain: ENC[AES256_GCM,data:knKyqKDQFGtDFaN1xp5cRBPNnhM=,iv:Ylz0q4ev/ePV+bMWxYM2okCoyvgu+J+HEa//K4+fTcI=,tag:RdH+qwWFoWoswbffxe/LMw==,type:str]
  serviceDomainOld: ENC[AES256_GCM,data:TxZv7qa3rgpfock13VCdiaOGgqGT,iv:Qk+aOBwVcpN8pPsAsJjCuFsQ2NCqF53WrqTAPgz3ObQ=,tag:hHsUoDDeLmBftiv0vuU0OQ==,type:str]
  k8s00Domain: ENC[AES256_GCM,data:EKBvtz2YqhJm628EGKPRaDsd,iv:h9HgcwZv0eGSvkvlnOVTxwVZM+64EcewCJeAkJK51XI=,tag:yeaoqlmQ9jEq97OCfKDomw==,type:str]
  k8s00DomainOld: ENC[AES256_GCM,data:lyi5BW26g0cENmtxBYp1VVJR0Q==,iv:gesiXsL9VXLUUHzDz8PPzYDdn1hcf6jVGHH+iHEbSbY=,tag:qYJ2bGdWlzAGvBYxUsjJuA==,type:str]
  piholeUrlMgmtBootstrap00: ENC[AES256_GCM,data:qoKSxZ3jR9xrVMcEEawoyYyrG1WdJStNvS0lv/SGhH9iTsu/d+i8djHmgA/uns14DQ==,iv:L1apPtbzs5SmIUqONf+mUYDmoQ3u8OaWkZJJptZNmvE=,tag:REFcTM1XRFMJ/OKoBOlONw==,type:str]
  piholeUrlMgmtK8s00: ENC[AES256_GCM,data:dwf+sFV8DXiyEhLcuO2Vj+E01oGZthDkI7oEFyu4Uxssq1wbXyjW0dFIGQ==,iv:XY7N2LvnF4yxr52PqQr9tpiXQAM9Ezz+tW62hSpywPU=,tag:jK2Vt5ZkkEWGFeE4x9H1mQ==,type:str]
  piholeUrlMgmtK8s00Internal: ENC[AES256_GCM,data:6VC2rihMJhFabrc7NtheCQumnCBoJK7+rmQ8dwA=,iv:Xp4O8fGN7Qe6FugBtBbpwURFSEmYOUQraXJceEAM2fM=,tag:CjwuIvSpeMmVk3lX8vMdJA==,type:str]
  piholeIpv4MgmtK8s00: ENC[AES256_GCM,data:UC62pO440tQlnBo=,iv:unentwg99dzrqsr+kmd4SsDCTRWkH0QwMwaBksnfWGw=,tag:Ybj1gulfHlZ/BKiQYia0/w==,type:str]
  piholeIpv6MgmtK8s00: ENC[AES256_GCM,data:RcX1j8cKRY9+j23soeytMXbtmmFuwA==,iv:IJzNxmT0fFsz725hQgIG8AZ0TPCfI2L+/jq9hr7YzZk=,tag:ZJ+xgm1LDRRWB3isXpc+Aw==,type:str]
  piholeIpv4K8s00Bootstrap00: ENC[AES256_GCM,data:qfBxfyr+pU5NJRfu,iv:kW84pgfnp/D7s7bXcz43ALR/NzH61NOU5poYDlRiEVA=,tag:Z2vxhGtK5qlQVyX3EWig8Q==,type:str]
  piholeIpv6K8s00Bootstrap00: ENC[AES256_GCM,data:jYczQKL61qxvsrQddp7EvLteYyk1WA==,iv:n/O+jLtaISy/EnJKHCJoQTDHYK1ulgwv3PAS7fLDzcE=,tag:E9GNL7fqNN4RkIqqpOV0EA==,type:str]
  piholeIpv4K8s00K8s00: ENC[AES256_GCM,data:gX9enfLgvbapilVq,iv:kUvBms8uh40LR4DV/Hu/+ZSy8L1O07SdqPOclTas4r8=,tag:Blypb8bxBgyiSji5ryDhkA==,type:str]
  piholeIpv6K8s00K8s00: ENC[AES256_GCM,data:pznTX/HBqO0ek8FAIjW8MfmQjKqRbA==,iv:6yy+GM9yqjI460YL/DjDxmyskFJdNXVacty3Sf72cFM=,tag:RH7YL2nvcC4/pbVF4Y53uQ==,type:str]
  piholeIpv4ServiceBootstrap00: ENC[AES256_GCM,data:C00MbSZMo8IaOHI5,iv:KRKs/x0lOB345VZLUPoNCq2z38uLo5IEzGUi4ngpmIw=,tag:JDfxG3npv3Li8ExWpVmDJg==,type:str]
  piholeIpv6ServiceBootstrap00: ENC[AES256_GCM,data:26h5G7T0R8ch9nvgq1rAoxE51nHbyQ==,iv:kTM+VeX+drDYCNvpOfRqRVNDST8r9n7HEUHNn+llhFI=,tag:Y2M3N53kRqiFD3hDOwUjfA==,type:str]
  piholeIpv4ServiceK8s00: ENC[AES256_GCM,data:tgxlKaseplFZullM,iv:ZzMdp1MqvUAui+xvYAQKaQMIQwBlKQzk60hNdN0UHU4=,tag:fME1OZ/+sxVbwEQjWkhoUw==,type:str]
  piholeIpv6ServiceK8s00: ENC[AES256_GCM,data:TfmeZ2utb0da1BOlKY4uUZS3RBLO/w==,iv:1+mhly/RHrO/MLWd1IVgG4BJ41Mbn0y1rnlBjzrRMRA=,tag:vB93RX9CDbODkDNiT89Vtw==,type:str]
  piholeIpv4CasaK8s00: ENC[AES256_GCM,data:NQ5MW7UOgPlf/74D,iv:Lu2ElPJQouGSlmjVgJriFV6lefoUPL9zQrM5C12pMew=,tag:f4ou8w2S03Hys+IcbD8OhA==,type:str]
  piholeIpv6CasaK8s00: ENC[AES256_GCM,data:EiJke7cCg8DClPnyu31kNNhVOA/07w==,iv:w7XJZZ9XRDV1aag8348ojVXLM7iA+pHfD9JFi6k6FPw=,tag:qz3VcWEVE38ZRIAYY1Q5Lg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ0RKS3NldlgzdUJBdkVq
        S01HWWNTZVRNbVFDRElzelg5dCtiU0MvTWpRClVvdlVCV0gxWXp1eHdDaGpoeEpi
        cC93TysrUkdoV052aEJaR2s0MGthOFkKLS0tIDU5V3VPS0RCdVR3SFdzY2pjVVFx
        WldtNFVua1oxSGVYVUZhdTFKd09YeDQKPRdyxqTs2nAtziEEaxh4ggAVia5UKUeQ
        wRwnpZN5B7Zs9dj28BzILiiu5NiKonj1QoPe3Sl/38mltB9Tdw2Kjw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T21:34:32Z"
  mac: ENC[AES256_GCM,data:yeN6rL0y+anYD/vjIS7Pjo0IgmArdxVew3hTvyr7ytBK3fPdRUIkh9zBAe0PDzycSe6ARKP0EypMoDMf1jgzxEUi98mJXXKRNU+WmFYWJATb5pJ/CX0CHe8ho1Du7TscP04TsvXqibyl/uCX4Yk6fuavKWvCXdLFqXlLlJ6Sfas=,iv:8n+ptdhBUhhfn+jLeCCEf6wKswmIyIhdg9+r/XCsU6c=,tag:9P1kZ5lcjE+CkhHTWDZKIA==,type:str]
  version: 3.13.1
