apiVersion: v1
kind: Secret
metadata:
  name: step-issuer-secret-values
  namespace: flux-system
stringData:
  url: ENC[AES256_GCM,data:uK0pvj8+9pocEnpSH/oZd0Op7pkD/q4a8q3V2hUqxUE=,iv:u/xvibSG0iuUxUsqIZmYoRye44E6P3sy0dUQVWMCyBo=,tag:0xxaCitt0rr6spBY6Tc3TQ==,type:str]
  caBundle: ENC[AES256_GCM,data:8LliG4+nsJ7pokw44dVxZOmtf5LdWDIToGzHFxMAObvktyiAyzZGPdH39hgXAfqJLfIcouBIEVQGKxCLCFbE8Bo7OL8T9zYHgtT2Pg/sPs93ATGFHPTrkumhIblnn2NooMttC0zRGtXnU3K3m6jsNDGu7v21gEfz+Pi4H8CJUZiCJztotRZpEJiVVExGmpjLs5+lWbmelpGcLgMkxNx40rQuMxyj6HKIDsu5x2Q3LK6MvClFCTcwpZZzj9UDCnI/qV3d13U/Shpf43/9NGIVXfeDv6irEbmtj8pOVr9o+MudZOGFyo4MQnot8J5WdPphWLE7doVioJ4kwr+P7T26+FZNaUYnw4iXVMWqL7PhFBy39V2lTjkMIMrrV1Iqmo6WhS7lsqGcAoUsqb+1Ro12rATNmXf1ObhAgFPDIMBfUpSI6Mk23epaNM4scSAM+WQN3AG2oLGpvUPvEFmIvHewU39sJ7gGNDM9seTX8Os4Q5NreUkKac3MHa854vcy+UXCo7bUcZuJPuagfuqlT0Vooqr42/pmQfF+AQhNIOrWAkM/j7y1/KM27fBD+/I26Hh1WBfj5oq2zmF5i6L/lwlt0XMw7bckS3hFG899j4HjkeY6d9Z3Pf3fLSgvU7aJBIaGeW4axTm9N28Nv29erYEi7Ekm1Qtp0mfRkvhOVDh6kfmRcbMHB5heJFdS/ExVx2r19gnQCzM5WZSagCOnh6117z+eG9fJ9EHl4RrdoCT+2THl62HqYD8PzDtb8MC96lx3vRjqiLZp1+oPpH4XkbvBHqB/ZIYSgujYuLXDFXP8pavI80ORonusL75r7A==,iv:jfiTF0jr6PG+9+Q4k8iQ11Zs8eHuqhkp+4pWo9HlMxA=,tag:m+lESRE06WL+tLHvYoFQHw==,type:str]
  name: ENC[AES256_GCM,data:7E/+h8Enp4zl4BBky2g=,iv:F8wXc5JtwuHWSKOUn6KDFO4+wDmbG24Hg7sofBaoC1k=,tag:gUeY5wRvUsrto6xM3IfB+Q==,type:str]
  kid: ENC[AES256_GCM,data:AFfsoalCQ5+Ts8a6R7LuWjCwNUGHzvGE3LOCFNLjq3gYYx/uwp2WpNOALA==,iv:3+BGgRXXBX7NmMFa0psif/CkW9NHXWqNUn0X9eFmlvo=,tag:Z6e6o5uyDoq1UnV7ZRNA3A==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RzV5UkF1alBHOEVkdGRj
        ckQ5YnRnSmN4QVNQWVMwdTI2c3ZxU3RoZkU0CjdQdXpuQ2I2bjRsdlRYNjBFVDAx
        b3FCM2tNbFVNbnpoVlRyNDZJYkI2Zk0KLS0tIGM4SVRSTnVJa04xa21HMWtLN3Jh
        WjNrUTRhUGhtbFB4UHltb3U2QVgvaTQKz/44NAoT6XwCsuEzv6uveK8WZHs5bYbY
        Yi/LUM+WuPy2kBU+RDRIw4Osec8FFD9piG8zMUYtJRcEi4OmB0q+Pg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-29T22:33:53Z"
  mac: ENC[AES256_GCM,data:tQlzwJYmnZA/t1Uf4stLZ/d7OZcRDNltzY468x3Cvb6keeb/eN9l/mzAvNgOzfMjYMkaopQYKsH2uX+TFPkAf2cT/oEzSiHxBn4MW2t6kDyHvejzCbjqXoTZbjWlPXI4OPcoYnwIvtQvnxF2CFZsEbQoP0B/ZAf7/wG0ygoE474=,iv:jH30/JYyB40Rkdti2EfJVd8TokQrBGmOJQJURr614AE=,tag:HpncMlJO74L+71G+vOei4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
