apiVersion: v1
kind: Secret
metadata:
  name: garage-creds
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=GKcbbecd219f0414936e4d9f4a
    aws_secret_access_key=848c3297a474fd7ddac81f6b0c55abb8ad0236dd785e541e2ac3a72a79533d6a
    region=garage
