apiVersion: v1
kind: Secret
metadata:
  name: garage-creds
  namespace: velero
type: Opaque
stringData:
  cloud: ENC[AES256_GCM,data:RAXaoEiLyULu9+92FZX/MEhoU7ZZByn+7QF71mnhJ3DpDgZfklYE5l+kMzQTSY90MfP9Erma5FOHXfbQH0PN3x9a2Tc8GA8GNX2HcLskVmq4s50fwo8mBT42s6H3YbwV1OhpMaxIJBC4zJw+/V13nM3hw7BVayHyIQMyoYrUcoC9DPbp/XrHpSiauc75zupv871XfeUqcyYGwbmO,iv:dm4dzmGk0jljyD7zASrUSt5sTNN6H6BgP6Ze68HORuE=,tag:vdMU7fPAYrBQNSpRwwMWPw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RjFVTGNCbCtNWm1ub3Vz
        cXVhZ2czeFVBMGlNWWk2bEFYanVVbko1L1FnCmhVeTliQVpZN1U0bmxHZmRLVXBS
        N1c4TVI4RWFzdUI2eU9BZ1hMVWpHWlEKLS0tIGJBUXpLWXBSOVRxelFIa3hlY2tD
        NHAvYytiQW5pa0VmVTRIVDFVdnpDeWcKeVdzdZNzdYH4ugclEbZWOj7kDvM5Ttai
        8gZgCkHJPcIS7kU4qeCxCI2jKmESb4iDAO+7XTmZqh2YAjT+cKtEWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-04T02:00:13Z"
  mac: ENC[AES256_GCM,data:9Mgfwq8T1wOU5GXUE0xDbccSvpiwPMxPTa07c2A4i3QmLpITqXJuEZhL3jWE11XdGwYNW+2sz6xuV8s4nW3rmZHwDxJHB3N3W4ExcUVdErQZzlH6bFpvtsHr2db3SPB/MPmgTSgni/lJqeSnvqzB59wuSSbtG3cy0BjE7Zwc0E4=,iv:A7aaCKRYkZZYeYVyaMqU7gghjm2rlUDfqeRmAdJO5M8=,tag:4TiBQWbicmEw5IckQZYwLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
