---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1440m
  url: https://vmware-tanzu.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 30m
  chart:
    spec:
      chart: velero
      version: ">= 10.1.0 < 10.2.0"
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: velero
      interval: 1m
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.12.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      privileged: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        spec:
          - alert: VeleroBackupFailed
            annotations:
              message: Velero backup {{ $labels.schedule }} has failed
            expr: |-
              velero_backup_last_status{schedule!=""} != 1
            for: 15m
            labels:
              severity: warning
          - alert: VeleroBackupFailing
            annotations:
              message: Velero backup {{ $labels.schedule }} has been failing for the last 12h
            expr: |-
              velero_backup_last_status{schedule!=""} != 1
            for: 12h
            labels:
              severity: critical
          - alert: VeleroNoNewBackup
            annotations:
              message: Velero backup {{ $labels.schedule }} has not run successfuly in the last 30h
            expr: |-
              (
              rate(velero_backup_last_successful_timestamp{schedule!=""}[15m]) <=bool 0
              or
              absent(velero_backup_last_successful_timestamp{schedule!=""})
              ) == 1
            for: 30h
            labels:
              severity: critical
          - alert: VeleroBackupPartialFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups
            expr: |-
              rate(velero_backup_partial_failure_total{schedule!=""}[25m])
                / rate(velero_backup_attempt_total{schedule!=""}[25m]) > 0.5
            for: 15m
            labels:
              severity: warning
    credentials:
      useSecret: true
      existingSecret: garage-creds
    backupsEnabled: true
    snapshotsEnabled: true
    configuration:
      backupStorageLocation:
        - name: velero-backups
          provider: aws
          bucket: "velero"
          config:
            region: "garage"
            s3ForcePathStyle: true
            s3Url: https://garage.garage
      volumeSnapshotLocation:
        - name: velero-snapshots
          provider: aws
          config:
            region: "garage"
            s3ForcePathStyle: true
            s3Url: https://garage.garage
    schedules:
      midnight:
        disabled: false
        schedules: "0 0 * * *"
        template:
          ttl: 720h0m0s  # 30 days
          # # See: https://velero.io/docs/v1.14/resource-filtering/#excludes
          # excludedNamespaceScopedResources:
          # - persistentVolumeClaims
          # excludedClusterScopedResources:
          # - persistentVolumes
          storageLocation: velero-backups
          # includedNamespaces:
          #   - yarr
          includedResources:
            - "PersistentVolumeClaim"
          labelSelector:
            matchLabels:
              velero-backup: "true"
          snapshotVolumes: true
          volumeSnapshotLocations:
            - velero-snapshots
          snapshotMoveData: true
          datamover: velero
      noon:
        disabled: false
        schedules: "0 12 * * *"
        template:
          ttl: 720h0m0s  # 30 days
          # # See: https://velero.io/docs/v1.14/resource-filtering/#excludes
          # excludedNamespaceScopedResources:
          # - persistentVolumeClaims
          # excludedClusterScopedResources:
          # - persistentVolumes
          storageLocation: velero-backups
          # includedNamespaces:
          #   - yarr
          includedResources:
            - "PersistentVolumeClaim"
          labelSelector:
            matchLabels:
              velero-backup: "true"
          snapshotVolumes: true
          volumeSnapshotLocations:
            - velero-snapshots
          snapshotMoveData: true
          datamover: velero
    deployNodeAgent: true
    features: EnableCSI
