---
- name: "[Consul] - Add Hashicorp repository"
  kubernetes.core.helm_repository:
    repo_name: "hashicorp"
    repo_state: "present"
    repo_url: "https://helm.releases.hashicorp.com"

- name: "[Consul] - Generate consul-values.yaml"
  ansible.builtin.template:
    dest: "{{ config_directory_path }}/consul-values.yaml"
    src: "consul-values.yaml"

- name: "[Consul] - Install and setup Consul"
  kubernetes.core.helm:
    chart_ref: "hashicorp/consul"
    create_namespace: yes
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    release_name: "consul"
    release_namespace: "consul"
    update_repo_cache: yes
    values_files:
      - "{{ config_directory_path }}/consul-values.yaml"
    wait: yes
    wait_timeout: "15m"

- name: "[Consul] - Wait till consul is created"
  kubernetes.core.k8s_info:
    kind: Pod
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    name: consul-server-0
    namespace: consul
    wait: yes
    wait_sleep: 5
    wait_timeout: 900