apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaizoku
  labels:
    app: kaizoku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaizoku
  template:
    metadata:
      labels:
        app: kaizoku
    spec:
      containers:
        - name: redis
          image: docker.io/redis:alpine
          imagePullPolicy: Always
        - name: kaizoku
          image: ghcr.io/oae/kaizoku
          env:
            - name: DATABASE_URL
              value: postgresql://kaizoku:tqqq2NvFgRHfujlBQwqgD9wfGcNDRwoNFRVAVhuwM22GpFwF5jvRxLyYnJWlSPsi@pg00-rw.database:5432/kaizoku
            - name: KAIZOKU_PORT
              value: "3000"
            - name: REDIS_HOST
              value: "127.0.0.1"
            - name: REDIS_PORT
              value: "6379"
            - name: PUID
              value: "65532"
            - name: PGID
              value: "65532"
            - name: TZ
              value: America/Toronto
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: manga-library
              mountPath: /data
            - name: config
              mountPath: /config
            - name: logs
              mountPath: /logs
      volumes:
        - name: manga-library
          persistentVolumeClaim:
            claimName: manga-library
          # emptyDir: {}
        - name: config
          emptyDir:
            sizeLimit: 500Mi
        - name: logs
          emptyDir:
            sizeLimit: 1Gi
