apiVersion: v1
kind: Secret
metadata:
  name: searxng
  namespace: searxng
stringData:
  openMetrics: ENC[AES256_GCM,data:WNYphdMUg9hsZud75qk8sQ==,iv:olCCV9d+AItszYq8FLopZuBG2z3RGnbS5oyt25Srh/Q=,tag:pFAe/p34SgsupLei3AC5rg==,type:str]
  secretKey: ENC[AES256_GCM,data:qcqMNie6djsMbu+yPF1pLZveAU9z5UY0CITX0vwfwLzi1dCIeCRvIWHVNr1+C8n0Yu/l1uGy+lvBQrOdUVROzg==,iv:lUcoPRj7m6FGOknj7qnDPWi+Pt9uiSzqMRtV5IkOs/E=,tag:ASgfkn1ch3MTWhF3kY8jHA==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZ3N1dURlajlUUFlveFhp
        UVFEZVF5ZmQvYjFEblpuSUppYUdGVmtaWENRCmhhSXYwTXFwdXNCdHNmV1lsaVFt
        eDU4Uk9wRmJwdVUvVmwwSzNGY0tDcG8KLS0tIDd4OUYrbkxkZ3NBNkNUYWl4dFlI
        RU0wb2dhQ1NoNUc1WmJpRVZlOHZEZlUKNRDQFnd4d2pBiWDy+9UsWgh08gTyMvjJ
        Y+3rzEOeBctTUeFQEyMVKahA1JR0+61JReznSVwNBY0ZMYE7y1rLxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T03:25:21Z"
  mac: ENC[AES256_GCM,data:Me6zCflpb61uG+d3gJL2ZgPRX0htKN9fArGhv0D97Xl1S2Z33fA+OlPGAgWjGtQLLvMR5hSI/k/MPbDD+9dL1Y7qODc4SLMgfmtNFYXGDEsZlUe6max+bhyUzeaRPgqG63uwU2HQsBABqYJRDt69d9kP6wUUhSvrX7pKMGxu7Io=,iv:oQuxnZzCEg5PP1xRmzTHNzejL4ur/y38T4k0K6hHaO0=,tag:dPHc6RLgzPBqM7CLckO95w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
