---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cnpg-image-catalogs
  namespace: database
spec:
  interval: 1440m
  url: https://github.com/cloudnative-pg/artifacts
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-image-catalogs
  namespace: database
spec:
  interval: 1440m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: cnpg-image-catalogs
  path: ./image-catalogs
  prune: true
  wait: true
---
# cloudnative-vectorchord
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: vectorchord
  labels:
    images.cnpg.io/family: vectorchord
    images.cnpg.io/publisher: vectorchord.ai
spec:
  images:
  - major: 18
    image: ghcr.io/tensorchord/cloudnative-vectorchord:18.3@sha256:392b53675b403d6a2c72b673cc488a7c272514755dd818c622fb9ce4665193c4
  - major: 17
    image: ghcr.io/tensorchord/cloudnative-vectorchord:17.9
  # Mainly for Immich. See: https://docs.immich.app/administration/postgres-standalone/#prerequisites
  - major: 16
    image: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
