---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cnpg-image-catalogs
  namespace: database
spec:
  interval: 1440m
  url: https://github.com/cloudnative-pg/artifacts
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-image-catalogs
  namespace: database
spec:
  interval: 1440m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: cnpg-image-catalogs
  path: ./image-catalogs
  prune: true
  wait: true
---
# cloudnative-vectorchord
# Mainly for Immich. See: https://docs.immich.app/administration/postgres-standalone/#prerequisites
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: vectorchord
  labels:
    images.cnpg.io/family: vectorchord
    images.cnpg.io/publisher: vectorchord.ai
spec:
  images:
    - major: 18
      image: ghcr.io/tensorchord/cloudnative-vectorchord:18.6-1.1.1
    - major: 17
      image: ghcr.io/tensorchord/cloudnative-vectorchord:17-1.1.1
