---
- name: "Restart infnoise"
  ansible.builtin.service:
    name: "infnoise.service"
    state: restarted
    enabled: true
  when:
    - certificate_authority_server_infnoise_this.stat.exists

- name: "Restart polkit"
  ansible.builtin.service:
    name: "polkit.service"
    state: restarted
    enabled: true
  when:
    - cas.yubikey.enabled | default(false)
