apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: kube-system
spec:
  interval: 1440m
  url: https://github.com/kubernetes-csi/external-snapshotter
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-crds
  namespace: kube-system
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  path: "./client/config/crd"
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-controller
  namespace: kube-system
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  path: "./deploy/kubernetes/snapshot-controller"
  prune: true
  timeout: 1m
