---
all:
  hosts:
    localhost:
      ansible_connection: local

    nameserver_old:
      ansible_port: 22
      ansible_user: "root"
      ansible_host: "{{ network.zones.us_east.hosts.nameserver | ansible.netcommon.ipaddr('address') }}"
      hosts:
        - "nameserver_old"

    nameserver:
      ansible_port: 2222
      ansible_user: "root"
      ansible_host: "{{ network.zones.us_east.hosts.nameserver | ansible.netcommon.ipaddr('address') }}"
      hosts:
        - "nameserver"

  children:
    home:
      hosts:
        reverseproxy:
          ansible_host: "{{ network.zones.home.hosts.reverseproxy.lab | ansible.netcommon.ipaddr('address') }}"
          ansible_user: "reverseproxy"
          hosts:
            - "reverseproxy"

        nas:
          ansible_host: "{{ network.zones.home.hosts.nas.lab | ansible.netcommon.ipaddr('address') }}"
          ansible_user: "nas"
          hosts:
            - "nas"
            - "nas.lan"

        print:
          ansible_host: "{{ network.zones.home.hosts.print.lab | ansible.netcommon.ipaddr('address') }}"
          ansible_user: "print"
          hosts:
            - "print"

      children:
        k3s_all:
          vars:
            ansible_user: "k3s"
            jump: "reverseproxy"
            identity_file_path: "/home/user/.ssh/k3s_ed25519"
          children:
            k3s_masters:
              hosts:
                "k3s-master-a":
                  ansible_host: "{{ network.zones.home.hosts['k3s-master-a'].k8s | ansible.netcommon.ipaddr('address') }}"
                  hosts:
                    - "k3s-master"
                    - "k3s-master-a"

            k3s_nodes:
              hosts:
                "k3s-node-a":
                  ansible_host: "{{ network.zones.home.hosts['k3s-node-a'].k8s | ansible.netcommon.ipaddr('address') }}"
                  hosts:
                    - "k3s-node-a"

                "k3s-node-b":
                  ansible_host: "{{ network.zones.home.hosts['k3s-node-b'].k8s | ansible.netcommon.ipaddr('address') }}"
                  hosts:
                    - "k3s-node-b"

                "k3s-node-c":
                  ansible_host: "{{ network.zones.home.hosts['k3s-node-c'].k8s | ansible.netcommon.ipaddr('address') }}"
                  hosts:
                    - "k3s-node-c"

                "k3s-node-d":
                  ansible_host: "{{ network.zones.home.hosts['k3s-node-d'].k8s | ansible.netcommon.ipaddr('address') }}"
                  hosts:
                    - "k3s-node-d"


  vars:
    timezone: "UTC"

    network:
      nameservers:
        default:
          - "1.1.1.1"
          - "1.0.0.1"
        block_malware:
          - "1.1.1.2"
          - "1.0.0.2"
        block_malware_porn:
          - "1.1.1.3"
          - "1.0.0.3"
      zones:
        "us_east":
          hosts:
            nameserver: "123.221.123.221/255.255.255.0"
        home:
          lans:
            guest:
              cidr: "192.168.0.0/24"
              gateway: "192.168.0.1"
            main:
              cidr: "192.168.1.0/24"
              gateway: "192.168.1.1"
            work:
              cidr: "192.168.2.0/24"
              gateway: "192.168.2.1"
            k8s:
              cidr: "192.168.3.0/24"
              gateway: "192.168.3.1"
            lab:
              cidr: "192.168.4.0/23"
              gateway: "192.168.4.1"
              wifi:
                wifi_name: "lab"
                wifi_password: "password"
          hosts:
            reverseproxy:
              guest: "192.168.0.5/255.255.255.0"
              main: "192.168.1.5/255.255.255.0"
              work: "192.168.2.5/255.255.255.0"
              k8s: "192.168.3.5/255.255.255.0"
              lab: "192.168.4.5/255.255.254.0"
              external: "192.168.4.10/255.255.254.0"
            print:
              lab: "192.168.4.7/255.255.254.0"
            nas:
              k8s: "192.168.3.20/255.255.255.0"
              lab: "192.168.4.6/255.255.254.0"
            "k3s-master-a":
              k8s: "192.168.3.2/255.255.255.0"
            "k3s-node-a":
              k8s: "192.168.3.5/255.255.255.0"
            "k3s-node-b":
              k8s: "192.168.3.6/255.255.255.0"
            "k3s-node-c":
              k8s: "192.168.3.7/255.255.255.0"
            "k3s-node-d":
              k8s: "192.168.3.8/255.255.255.0"


    ssh_key: |
      SSH key here


    ssh_config:
      default_identity_file_path: "/home/user/.ssh/user_ed25519"
      ansible_hosts: yes
      hostnames:
        - hosts:
            - "github.com"
          user: "git"
          hostname: "github.com"