---
home:
  vars:
    timezone: "UTC"
    k3s_ssh_key: "password"


    logrotate:
      - name: "ansible_default"
        log_path:
          - "/var/log/alternatives.log"
          - "/var/log/auth.log"
          - "/var/log/syslog"
        options:
          - "compress"
          - "delaycompress"
          - "create 644"
          - "daily"
          - "missingok"
          - "rotate 30"
          - "size 500M"
          - "notifempty"
          - "copytruncate"
          - "dateext"


    fail2ban_config_template:
      ignore_ip:
        - "127.0.0.1/32"
        - "::1"
        - "{{ ansible_default_ipv4.address }}"
      bantime: "31536000" # 60*60*24*365 (1 year)
      findtime: "3600" # 1 hour
      maxretry: "2"
      jails:
        - name: "sshd"
          port: "ssh"
          logpath: "%(sshd_log)s"
          backend: "%(sshd_backend)s"
          options:
            mode: "aggressive"


    k3s:
      config:
        cluster:
          ip: "{{ network.zones.home.hosts['k3s-master-a'].k8s | ansible.netcommon.ipaddr('address') }}"
          ip_netmask: "{{ network.zones.home.hosts['k3s-master-a'].k8s | ansible.netcommon.ipaddr('host') }}"
          port: 6443
        address_pools:
          # Keep 192.168.3.20 to 192.168.3.29 free for external service that k8s will need (e.g. nfs)
          - "192.168.3.30-192.168.3.253"
        nameservers: "{{ [network.zones.home.lans.k8s.gateway, network.nameservers.block_malware] | flatten }}"
        k8s_gateway:
          domain:
            - "lan"
            - "pihole-guest"
            - "pihole-main"
            - "pihole-work"
            - "pihole-lab"
          watchedResources:
            - "Ingress"
            - "Service"
          ttl: 60
          loadBalancerIP: "192.168.3.31"
        nfs:
          - replicas: 3
            server: "{{ network.zones.home.hosts.nas.k8s | ansible.netcommon.ipaddr('address') }}"
            path: "/mnt/zfs/nas/k3s"
            name: "k3s"
            default: true
        vault:
          storage:
            type: "postgresql"
            username: "vault"
            password: "password"
            address: "{{ network.zones.home.hosts.reverseproxy.lab | ansible.netcommon.ipaddr('address') }}"
            port: 5432
            database_name: "vault"
            ssl_mode: "disable"
          server:
            ingress:
              host: "vault.k3s.lan"
            ha:
              replicas: 3
        pihole:
          - name: "guest"
            persistentVolumeClaim:
            replicaCount: 2
            ingress:
              hosts:
                - "pihole.guest.lan"
            dns1: "{{ network.nameservers.block_malware[0] }}"
            dns2: "{{ network.nameservers.block_malware[1] }}"
            doh:
            service_dns:
              ip:
                static: "192.168.3.32"
            adlists:
              - "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts"
              - "https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt"
          - name: "main"
            persistentVolumeClaim:
            replicaCount: 2
            ingress:
              hosts:
                - "pihole.main.lan"
            dns1: "{{ network.nameservers.block_malware[0] }}"
            dns2: "{{ network.nameservers.block_malware[1] }}"
            doh:
            service_dns:
              ip:
                static: "192.168.3.33"
            adlists:
              - "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts"
              - "https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt"
          - name: "work"
            persistentVolumeClaim:
            replicaCount: 2
            ingress:
              hosts:
                - "pihole.work.lan"
            dns1: "{{ network.nameservers.block_malware[0] }}"
            dns2: "{{ network.nameservers.block_malware[1] }}"
            doh:
            service_dns:
              ip:
                static: "192.168.3.34"
            adlists:
              - "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts"
              - "https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt"
          - name: "lab"
            persistentVolumeClaim:
            replicaCount: 2
            ingress:
              hosts:
                - "pihole.lab.lan"
            dns1: "{{ network.nameservers.block_malware[0] }}"
            dns2: "{{ network.nameservers.block_malware[1] }}"
            doh:
            service_dns:
              ip:
                static: "192.168.3.35"
            customDnsEntries:
              - host: "pihole.guest.lan"
                ip: "{{ network.zones.home.hosts.reverseproxy.guest | ansible.netcommon.ipaddr('address') }}"
              - host: "pihole.main.lan"
                ip: "{{ network.zones.home.hosts.reverseproxy.guest | ansible.netcommon.ipaddr('address') }}"
              - host: "pihole.work.lan"
                ip: "{{ network.zones.home.hosts.reverseproxy.guest | ansible.netcommon.ipaddr('address') }}"
              - host: "pihole.lab.lan"
                ip: "{{ network.zones.home.hosts.reverseproxy.guest | ansible.netcommon.ipaddr('address') }}"
            adlists:
              - "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts"
              - "https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt"
      masters:
        - host: "k3s-master-a"
          ip: "{{ network.zones.home.hosts['k3s-master-a'].k8s | ansible.netcommon.ipaddr('address') }}"
          ip_netmask: "{{ network.zones.home.hosts['k3s-master-a'].k8s | ansible.netcommon.ipaddr('host') }}"
          port: 6443
      nodes:
        - host: "k3s-node-a"
          ip: "{{ network.zones.home.hosts['k3s-node-a'].k8s | ansible.netcommon.ipaddr('address') }}"
          ip_netmask: "{{ network.zones.home.hosts['k3s-node-a'].k8s | ansible.netcommon.ipaddr('host') }}"
        - host: "k3s-node-b"
          ip: "{{ network.zones.home.hosts['k3s-node-b'].k8s | ansible.netcommon.ipaddr('address') }}"
          ip_netmask: "{{ network.zones.home.hosts['k3s-node-b'].k8s | ansible.netcommon.ipaddr('host') }}"
        - host: "k3s-node-c"
          ip: "{{ network.zones.home.hosts['k3s-node-c'].k8s | ansible.netcommon.ipaddr('address') }}"
          ip_netmask: "{{ network.zones.home.hosts['k3s-node-c'].k8s | ansible.netcommon.ipaddr('host') }}"
        - host: "k3s-node-d"
          ip: "{{ network.zones.home.hosts['k3s-node-d'].k8s | ansible.netcommon.ipaddr('address') }}"
          ip_netmask: "{{ network.zones.home.hosts['k3s-node-d'].k8s | ansible.netcommon.ipaddr('host') }}"