---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: yarr
  name: multimedia
  labels:
    type: multimedia
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  capacity:
    storage: 10Ti
  storageClassName: ""
  nfs:
    server: "${jellyfin_multimedia_ip}"
    path: "${jellyfin_multimedia_path}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: yarr
  name: multimedia
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Ti
  storageClassName: ""
  selector:
    matchLabels:
      type: multimedia
