---
apiVersion: v1alpha1
kind: RegistryTLSConfig
name: harbor.service.${subdomain}
ca: |-
  -----BEGIN CERTIFICATE-----
  MIIBmzCCAUKgAwIBAgIRALL4VaexNNXD/oS0dQ8zTq8wCgYIKoZIzj0EAwIwLDEQ
  MA4GA1UEChMHaG9tZWxhYjEYMBYGA1UEAxMPaG9tZWxhYiBSb290IENBMB4XDTI1
  MTAxMzIwMjI1NloXDTM1MTAxMTIwMjI1NlowLDEQMA4GA1UEChMHaG9tZWxhYjEY
  MBYGA1UEAxMPaG9tZWxhYiBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
  QgAEvPyMIBy9b7HV/koqNb6216ZLGk57HzdGymYTDqeLlvbxck8dL5kmTSyUcy87
  9+xR80uwY3gACeiPcSJGJPkRnaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB
  /wQIMAYBAf8CAQEwHQYDVR0OBBYEFLJy0jDKFTVnIYBgoktz4A77ZLAmMAoGCCqG
  SM49BAMCA0cAMEQCIECuVsxylOTmL27vahaX43oNQXkGS4YicIr3kppvu7fgAiAs
  B6CBHi0oab6Ud/8MxNeKabB6TCQ44iXZPsnx6vm0Wg==
  -----END CERTIFICATE-----
