apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium/cilium.yaml
  - local-path-provisioner/local-path-provisioner.yaml
  - metrics-server
  - generic-device-plugin/generic-device-plugin.yaml
  - external-snapshotter/external-snapshotter.yaml
  - rook-ceph/rook-ceph.yaml
  - cert-manager/cert-manager.yaml
  - prometheus/helmRepository.yaml
