---
- name: "Helm - Add ingress-nginx repo"
  kubernetes.core.helm_repository:
    repo_name: "ingress-nginx"
    repo_state: "present"
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: "Helm - Install ingress-nginx"
  kubernetes.core.helm:
    chart_ref: "ingress-nginx/ingress-nginx"
    create_namespace: yes
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    release_name: "ingress-nginx"
    release_namespace: "ingress-nginx"
    release_values:
      controller:
        watchIngressWithoutClass: true
        metrics:
          enabled: true
        ingressClassResource:
          default: true
    update_repo_cache: yes
    wait: yes
    wait_timeout: "15m"