---
- name: "Install fail2ban"
  ansible.builtin.apt:
    name: "fail2ban"
    state: present

- name: "Generate filters"
  ansible.builtin.template:
    mode: "644"
    dest: "/etc/fail2ban/filter.d/{{ filter.name }}.conf"
    src: "filter.conf"
  loop: "{{ fail2ban_config.filters }}"
  loop_control:
    loop_var: "filter"
  when:
    - fail2ban_config.filters is defined

- name: "Create jail.local"
  ansible.builtin.template:
    mode: "644"
    dest: "/etc/fail2ban/jail.d/jail.local"
    src: "jail.local"

- name: "Restart fail2ban"
  ansible.builtin.service:
    enabled: yes
    name: "fail2ban"
    state: "restarted"
...