apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-creds
  namespace: admin
type: Opaque
stringData:
  pgadmin-password: ENC[AES256_GCM,data:GV99/oEE9DGDpAN8ZfIR,iv:UXe+eG/2PyfQPEPTXn2Vxd1jy1d/GM8qZCg8msYBqkw=,tag:QdbtFfkbiuheWMUZG3gHcA==,type:str]
  pgadmin-username: ENC[AES256_GCM,data:oH6gWSPLYDV4hbUgEg==,iv:qP7sQfzPdk3QVvEbIPEYmMHc/WJ4iRU9aoy/Fz8i+TY=,tag:Q/fCkAnqv41HI5xEAylANQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbjJTZVVHd09ZRStoNjBz
        RGVuSlpOdzkreUJScis2UnlsazFIZUNPMzBzCnZHZUhTZGhuWk9FMEF1QmEyTVg2
        QnBkWHpuZ0RzM2gvNE1lMzFtT0Z3RGMKLS0tIEVmM293WUsyRnFNMlNocTJNb1Nr
        OUYwbDlXaEQvc1J5S0w1QWtQLzhFNVUKZoz3+np2nZucomZON6wGrEKnGXuOcJNl
        8ES0XA6c9L0Jus25mvZOXy6TmXjNKF/pzbCcR8PvMI276py6TaTzbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T18:44:44Z"
  mac: ENC[AES256_GCM,data:bvXoOw/WqAJKNPOpO/RcnIvpQuUXYwZHR474mSdJYHCDIIZM7q+yiW0rjbyPEnZ9qY6wZRNrpo/DATnuvEUdAA5VFWFIvsbO2sjHq7/qRxUx7H61mjT6uKx3RBigO1E7Se+RaMcIorewm/+xJIRz7840X8U6HjqGjGd4mNu/Gd0=,iv:UVU2McPorIOQvsUPkHm0ZfB+2KhiX/NgCfiBHVdJkEI=,tag:xXw/NYsovjOD6qb2PLCzPg==,type:str]
  version: 3.13.3
