---
- name: "Install dependency"
  ansible.builtin.apt:
    name:
      - "build-essential"
      - "git"

- name: "Download repository"
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "/tmp/endlessh"
    repo: "https://github.com/skeeto/endlessh.git"
    version: "{{ endlessh_version }}"

- name: "Build Endlessh"
  community.general.make:
    chdir: "/tmp/endlessh"

- name: "Install Endlessh"
  community.general.make:
    chdir: "/tmp/endlessh"
    target: "install"

- name: "Create service"
  ansible.builtin.template:
    dest: "/usr/lib/systemd/system/endlessh.service"
    group: "root"
    mode: "644"
    owner: "root"
    src: "endlessh.service"

- name: "Reload daemon service and start Endlessh"
  ansible.builtin.service:
    daemon_reload: yes
    enabled: yes
    name: "endlessh.service"
    state: "restarted"