---
- name: "Create a k3s config directory"
  ansible.builtin.file:
    group: "root"
    mode: "600"
    owner: "root"
    path: "{{ config_directory_path }}"
    recurse: yes
    state: directory

- name: "[Vault] - include vault installation"
  ansible.builtin.include_tasks: "vault.yaml"
  when: k3s.config.vault is defined