---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: "service-k8s00-ipv4-64513"
      localASN: 64513
      peers:
        - name: "opnsense-service-k8s00"
          peerASN: 64512
          peerAddress: "192.168.40.1"
          peerConfigRef:
            name: "cilium-peer"
