#!/bin/sh

server_hostname=$(toilet {{ inventory_hostname }})
UPTIME_DAYS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)
UPTIME_HOURS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)
UPTIME_MINUTES=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)
ip_info=$(for __ip in `hostname -I`
do
echo "IP: "$__ip
done)

cat << EOD
#######################################################
$server_hostname
#######################################################

Uptime: $UPTIME_DAYS days, $UPTIME_HOURS hours, $UPTIME_MINUTES minutes
Memory: `free -mh | head -n 2 | tail -n 1 | awk {'print $3'}` / `free -mh | head -n 2 | tail -n 1 | awk {'print $2'}`
EOD
