---
- name: "Reload systemd-resolved"
  ansible.builtin.service:
    name: "systemd-resolved.service"
    state: "restarted"


- name: "Restart systemd-timesyncd"
  ansible.builtin.service:
    name: "systemd-timesyncd.service"
    state: restarted
