---
- name: "Get zfs mountpoint"
  ansible.builtin.shell: "zfs list | tail -n $(($(zfs list | wc -l)-1)) | awk '{print $5}' | grep {{ item.name }} || true"
  register: zfs_mountpoint

- name: "Create zfs"
  community.general.zfs:
    name: "{{ iter_pool.mountpoint_name }}/{{ item.name }}"
    state: present
  when:
    - item.state == "present"

- name: "Set zfs {{ iter_pool.mountpoint_name }}/{{ item.name }} properties"
  ansible.builtin.command: "zfs set {{ property.key }}={{ property.value }} {{ iter_pool.mountpoint_name }}/{{ item.name }}"
  loop: "{{ query('dict', item.option) }}"
  loop_control:
    loop_var: "property"
  when:
    - item.option is defined
    - property.value != zfs_mountpoint.stdout

- name: "Set snapshot to false by default"
  ansible.builtin.command: "zfs set com.sun:auto-snapshot=false {{ iter_pool.mountpoint_name }}/{{ item.name }}"
  when:
    - item.snapshot is not defined

- name: "Set snapshot options if defined"
  ansible.builtin.command: "zfs set {{ snapshot }} {{ iter_pool.mountpoint_name }}/{{ item.name }}"
  loop:
    - "com.sun:auto-snapshot=true"
    - "com.sun:auto-snapshot:monthly={% if item.snapshot.monthly is defined %}true{% else %}false{% endif %}"
    - "com.sun:auto-snapshot:weekly={% if item.snapshot.weekly is defined %}true{% else %}false{% endif %}"
    - "com.sun:auto-snapshot:daily={% if item.snapshot.daily is defined %}true{% else %}false{% endif %}"
    - "com.sun:auto-snapshot:hourly={% if item.snapshot.hourly is defined %}true{% else %}false{% endif %}"
    - "com.sun:auto-snapshot:frequent={% if item.snapshot.frequent is defined %}true{% else %}false{% endif %}"
  loop_control:
    loop_var: "snapshot"
  when:
    - item.snapshot is defined
...