---
- name: "Install zfs"
  become: yes
  ansible.builtin.apt:
    name:
      - zfsutils-linux
      - zfs-auto-snapshot
    state: "present"

- name: "Check if zpools are already setup and mount them"
  ansible.builtin.command: "zpool import -a -f"

- name: "Create zfs pools/filesystems"
  ansible.builtin.include_tasks: create_pools.yaml
  loop: "{{ zfs.pools }}"
  loop_control:
    loop_var: iter_pool

- name: "Remove zfs pools/filesystems"
  ansible.builtin.include_tasks: destroy_pools.yaml
  loop: "{{ zfs.pools }}"
  loop_control:
    loop_var: iter_pool

- name: "List of services to start after zfs-mount.service"
  ansible.builtin.lineinfile:
    firstmatch: yes
    insertbefore: "^Description="
    line: "Before={% for svc in zfs.before_service %}{{ svc }}{% if not loop.last %} {% endif %}{% endfor %}"
    path: "/etc/systemd/system/zfs.target.wants/zfs-mount.service"
  notify: "Service changed"
...