---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-certificates
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  chart:
    spec:
      chart: step-certificates
      version: ">= 1.28.4 < v1.29.0"
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: cert-manager
      interval: 1m
