---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-issuer
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  chart:
    spec:
      chart: step-issuer
      version: ">= 1.9.9 < 1.10.0"
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: cert-manager
      interval: 1m
