apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: internal
spec:
  controllerName: io.cilium/gateway-controller
  description: GatewayClass for internal network
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: GatewayClass
# metadata:
#   name: external
# spec:
#   controllerName: io.cilium/gateway-controller
#   description: GatewayClass for external network
