# https://github.com/smallstep/step-issuer?tab=readme-ov-file
apiVersion: certmanager.step.sm/v1beta1
kind: StepIssuer
metadata:
  name: step-issuer
  namespace: cet-manager
spec:
  url: "${url}"
  # curl --silent --insecure https://ca.service.home.enoxi.me/roots.pem | base64 -w0
  caBundle: "${caBundle}"
  provisioner:
    name: "${name}"
    kid: "${kid}"
    passwordRef:
      name: step-certificates-provisioner-password
      key: password
