---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-storage
  namespace: local-path-storage
spec:
  interval: 60m
  targetNamespace: local-path-storage
  sourceRef:
    kind: GitRepository
    name: local-path-provisioner
    namespace: local-path-storage
  path: "./deploy"
  prune: true
  timeout: 1m
  patches:
    - patch: |-
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: local-path-config
          namespace: local-path-storage
        data:
          config.json: |-
            {
                    "nodePathMap":[
                    {
                            "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                            "paths":["/var/mnt/local-path-provisioner"]
                    }
                    ]
            }
          setup: |-
                #!/bin/sh
                set -eu
                mkdir -m 0777 -p "$VOL_DIR"
          teardown: |-
                #!/bin/sh
                set -eu
                rm -rf "$VOL_DIR"
          helperPod.yaml: |-
                apiVersion: v1
                kind: Pod
                metadata:
                  name: helper-pod
                spec:
                  priorityClassName: system-node-critical
                  tolerations:
                    - key: node.kubernetes.io/disk-pressure
                      operator: Exists
                      effect: NoSchedule
                  containers:
                  - name: helper-pod
                    image: busybox
    - patch: |-
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: local-path
    - patch: |-
        apiVersion: v1
        kind: Namespace
        metadata:
          name: local-path-storage
