---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-gpu
spec:
  interval: 1440m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: ">= 0.17.2 < 0.18.0"
      sourceRef:
        kind: HelmRepository
        name: nvdp
      interval: 60m
  values:
    runtimeClassName: nvidia
    gfd:
      enabled: true
