---
- name: "Create a k3s config directory"
  ansible.builtin.file:
    group: "root"
    mode: "600"
    owner: "root"
    path: "{{ config_directory_path }}"
    recurse: yes
    state: directory

- name: "Install pip needed libraries"
  ansible.builtin.pip:
    executable: pip3
    name: openshift

- name: "Create Calico custom-resources"
  ansible.builtin.template:
    dest: "{{ config_directory_path }}/calico-custom-resources.yaml"
    src: "calico-custom-resources.yaml"

- name: "[Calico] - Download tigera-operator manifest"
  ansible.builtin.get_url:
    dest: "{{ config_directory_path }}/tigera-operator.yaml"
    url: "https://docs.projectcalico.org/manifests/tigera-operator.yaml"

- name: "[Calico] - Install tigera-operator manifest"
  kubernetes.core.k8s:
    apply: yes
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: "{{ config_directory_path }}/tigera-operator.yaml"
    state: "present"
    wait: yes

- name: "[Calico] - Install Calico custom ressources"
  kubernetes.core.k8s:
    apply: yes
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: "{{ config_directory_path }}/calico-custom-resources.yaml"
    state: "present"
    wait: yes

# - name: "[Calico] - Taint master nodes"
#   ansible.builtin.shell: |
#     KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl taint nodes --all node-role.kubernetes.io/master-