---
# Use --limit HOST, --ask-become-pass and -e ansible_user=YOUR_USERNAME <- Your local username $(whoami)
- name: Prepare dietpi systems
  hosts:
    - dietpi
  gather_facts: true
  connection: local
  tags:
    - prepare_dietpi
  become: true
  roles:
    - init_dietpi_headless


# Use --limit HOST, --private-key PRIV_SSH_KEY_PATH and, optional, -e ansible_host=HOST_IP
- name: Setup dietpi base
  hosts:
    - dietpi
  gather_facts: false
  tags:
    - setup_dietpi
  vars:
    ansible_user: root
  roles:
    - standardization
    - user_group


# Use --extra-vars ansible_user=YOUR_USERNAME <- Your local username $(whoami)
- name: Prepare flatcar ignition files
  hosts:
    - flatcar
  gather_facts: true
  connection: local
  tags:
    - flatcar_butane
  roles:
    - flatcar


# Use --extra-vars device_path=/dev/DEVICE <- Your sdcard path,
# --ask-become-pass and --extra-vars ansible_user=YOUR_USERNAME <- Your local username $(whoami)
- name: Prepare pikvm system
  hosts:
    - pikvm
  gather_facts: true
  connection: local
  tags:
    - prepare_pikvm
  become: true
  roles:
    - init_pikvm_headless


- name: Set up pikvm base
  hosts:
    - pikvm
  gather_facts: false
  tags:
    - setup_pikvm
  vars:
    ansible_user: root
    ansible_ssh_pass: root
    ansible_ssh_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no"
  pre_tasks:
    - name: Set the system as read-write
      ansible.builtin.raw: /usr/bin/rw
      register: rw
      changed_when: rw.rc == 0
  roles:
    - user_group
  post_tasks:
    - name: Set the system as read-only
      ansible.builtin.raw: /usr/bin/ro
      register: ro
      changed_when: ro.rc == 0
