---
- name: Certificate authority server
  hosts: ca
  gather_facts: true
  become: true
  roles:
    - base
    - go_lang
    - certificate_authority_server


- name: Setup docker containers
  hosts:
    - flatcar
  gather_facts: false
  become: false
  roles:
    - directories_files
    - docker_mgmt


- name: Set up pikvm
  hosts:
    - pikvm
  gather_facts: false
  become: true
  roles:
    - user_group
    - pikvm_config
