apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: ">=v1.17.6 <1.18.0"
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: rook-ceph
      interval: 15m
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    cephClusterSpec:
      storage:
        useAllNodes: true
        useAllDevices: true
    cephBlockPools:
      - name: rook-ceph-retain
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: rook-ceph-retain
          isDefault: false
          reclaimPolicy: Retain
          allowVolumeExpansion: true
      - name: rook-ceph-delete
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: rook-ceph-delete
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
    # cephFileSystems:
    #   - name: rook-cephfs-rwx-retain
    #     storageClass:
    #       enabled: true
    #       name: rook-cephfs-rwx-retain
    #       isDefault: false
    #       reclaimPolicy: Retain
    #       allowVolumeExpansion: true
    #   - name: rook-cephfs-rwx-delete
    #     storageClass:
    #       enabled: true
    #       name: rook-cephfs-rwx-delete
    #       isDefault: false
    #       reclaimPolicy: Delete
    #       allowVolumeExpansion: true
