apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 60m
  chart:
    spec:
      chart: rook-ceph
      version: ">=v1.17.6 <1.18.0"
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: rook-ceph
      interval: 15m
  values:
    monitoring:
      enabled: true
