apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-bgp
  namespace: kube-system
spec:
  interval: 5m
  path: ./kubernetes/clusters/k8s00/bgp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
