apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-bgp
  namespace: kube-system
spec:
  dependsOn:
    - name: cilium
  interval: 5m
  path: ./bgp/bgp.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
