apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: ">=1.17.5 <1.18.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 1m
  # valuesFrom:
  #   - kind: Secret
  #     name: cilium-helm-values
  values:
    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    bgpControlPlane:
      enabled: true
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    k8sServiceHost: localhost
    k8sServicePort: 7445
    cni:
      exclusive: false
    devices: br0
    # ingressController:
    #   enabled: true
    #   default: false
    #   loadbalancerMode: dedicated
    gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true
    encryption:
      enabled: true
      type: wireguard
      nodeEncryption: true
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - icmp
          - http
        enableOpenMetrics: true
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        ingress:
          enabled: false
          annotations: {}
          # kubernetes.io/ingress.class: nginx
          # kubernetes.io/tls-acme: "true"
          className: ""
          hosts:
            - chart-example.local
          labels: {}
          tls: []
          #  - secretName: chart-example-tls
          #    hosts:
          #      - chart-example.local
    ipv6:
      # -- Enable IPv6 support.
      enabled: true
    prometheus:
      metricsService: true
      enabled: true
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
