apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - HelmRelease.yaml
  - bgp.yaml
secretGenerator:
  - name: cilium-helm-values
    files:
      - values.yaml=values.sops.yaml
