---
directories_files:
  directories:
    - path: "/home/{{ ansible_user }}/traefik_config"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    - path: "/home/{{ ansible_user }}/docker_volume_backup_config"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  contents:
    - dest: "/home/{{ ansible_user }}/traefik_config/traefik.yml"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0644"
      content: |
        global:
          checkNewVersion: false
          sendAnonymousUsage: false

        entryPoints:
          mgmt:
            address: :80
          mgmtsecure:
            address: :443
          k8s00:
            address: :81
          k8s00secure:
            address: :444
          monitoring:
            address: :8082

        providers:
          docker:
            exposedByDefault: false
            network: traefik
            watch: true
          file:
            filename: /etc/traefik/ignorecert.yaml

        api:
          insecure: false
          dashboard: true
          disableDashboardAd: true

        metrics:
          addInternals: true
          prometheus:
            addEntryPointsLabels: true
            addRoutersLabels: true
            addServicesLabels: true
            entryPoint: monitoring

        certificatesResolvers:
          cainternal:
            acme:
              email: {{ cas_root_ca_provisioner }}
              caServer: https://ca.{{ mgmt_domain }}/acme/acme/directory
              caCertificates:
                - /etc/ssl/certs/homelab.pem
              caSystemCertPool: true
              storage: /certificates/acme.json
              keytype: EC384
              certificatesDuration: 2160
              httpchallenge:
                entrypoint: mgmt
              tlschallenge: {}
    - dest: "/home/{{ ansible_user }}/traefik_config/ignorecert.yaml"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      content: |
        http:
          serversTransports:
            ignorecert:
              insecureSkipVerify: true
    - dest: /etc/ssl/certs/homelab.pem
      owner: root
      group: root
      mode: "0644"
      content: "{{ root_ca_certificate }}"
    - dest: "/home/{{ ansible_user }}/docker_volume_backup_config/pihole_mgmt.env"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      content: |
        BACKUP_CRON_EXPRESSION='@daily'
        BACKUP_SOURCES="/custom_backup/pihole_mgmt"
        BACKUP_RETENTION_DAYS="30"
        AWS_S3_PATH="pihole_mgmt"
    - dest: "/home/{{ ansible_user }}/docker_volume_backup_config/pihole_service.env"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      content: |
        BACKUP_CRON_EXPRESSION='@daily'
        BACKUP_SOURCES="/custom_backup/pihole_service"
        BACKUP_RETENTION_DAYS="30"
        AWS_S3_PATH="pihole_service"
    - dest: "/home/{{ ansible_user }}/docker_volume_backup_config/pihole_k8s00.env"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      content: |
        BACKUP_CRON_EXPRESSION='@daily'
        BACKUP_SOURCES="/custom_backup/pihole_k8s00"
        BACKUP_RETENTION_DAYS="30"
        AWS_S3_PATH="pihole_k8s00"
    - dest: "/home/{{ ansible_user }}/docker_volume_backup_config/pihole_casa.env"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      content: |
        BACKUP_CRON_EXPRESSION='@daily'
        BACKUP_SOURCES="/custom_backup/pihole_casa"
        BACKUP_RETENTION_DAYS="30"
        AWS_S3_PATH="pihole_casa"
