apiVersion: v1
kind: Secret
metadata:
  name: yarr-secret-values
  namespace: flux-system
stringData:
  jellyfin_multimedia_ip: ENC[AES256_GCM,data:oP/ITYiixAYawfiBJA==,iv:bnBoXmVDJ5h2Rk6ZDnl5oLxeYD29sWI7A/f3oRhxiZk=,tag:VPp3xr5kK2oN11J0Cyk8iQ==,type:str]
  jellyfin_multimedia_path: ENC[AES256_GCM,data:2PvYhe8mjjjZjyj9RbhSMjkedw==,iv:Yx32NclzVWJXqngkTktKMq9xEt3qHQQjZE3S4jxni9Y=,tag:26m2H5S2ZpLq2g56wCypDg==,type:str]
  jellyfin_hostname: ENC[AES256_GCM,data:J53KQXE2KRcfhDu4Q/1jhjJXaUsBBtLiwhTjbU3KbQ==,iv:qFNkFAyXVVVr6I16WkRP7XMtpRP9/Edc9xQyLGnS1UQ=,tag:Up41SUJZduF5Uu/7sjzHgw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRmVHOEIvcFUydkZXOUFE
        QmJDM2U5WTNRZHZwQXVsbFluS2pJYzFUVG5jCnpGK05iUi9WUll4R1Y2V3lkUldU
        bWJhL0M0VmY3MkFKUlNkUFE4WEhNMWsKLS0tIEJjYyswSVc2dXZucTZPdDd4U1RG
        bVVOczFSNlR2T0NRQkdSSlRFQ3FqekUKQmfiuqBl2ycqnoVK7EzuJwB4tG+bmheZ
        TXnD8ftuN0dAGJu9FLY1V5bohGBX0TFGAyzB+RAvzi7EVbB7qiFF9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-16T16:43:03Z"
  mac: ENC[AES256_GCM,data:gCV/s8lF35nv9kgCuS1AsWyFUFtZZSngLr4V2KWmM4Ijmit2kj8QI8YG101DoB+Jvc64WSJwiMD9DheHPRoPI4VtfsAgmI70HbCqkHpLWL4GQfKLjcqqrlubJFjArj+213s6OyZnWi8u2tpOpIbAPsqTi8Aazs6NJk9rzBQV6SQ=,iv:ZkxjQDrZ5VLYZDUkgflxkVPDwPYsmo5n1UDOXCYsYcs=,tag:i3hcdFs5qY1KZGxfZy64fg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
