---
- name: "Create the directory"
  ansible.builtin.file:
    path: "temp/{{ inventory_hostname }}"
    recurse: yes
    state: directory
  delegate_to: localhost

- name: "Generate the user-data file for deployment"
  ansible.builtin.template:
    mode: "644"
    dest: "temp/{{ inventory_hostname }}/user-data"
    src: "user-data"
  delegate_to: localhost

- name: "Generate the network-config file for deployment"
  ansible.builtin.template:
    mode: "644"
    dest: "temp/{{ inventory_hostname }}/network-config"
    src: "network-config"
  delegate_to: localhost