apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-infra
  namespace: flux-system
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: kubernetes/infrastructure
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-age
  namespace: flux-system
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: kubernetes/clusters/k8s00
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
