apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure
  - ../../clusters/k8s00
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sops-age
  namespace: flux-system
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ../../clusters/k8s00
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
