---
- name: "Purge host key"
  ansible.builtin.command: "ssh-keygen -R {{ item.ip }}"
  loop: "{{ ssh_config.hostnames }}"
  when:
    - ssh_config is defined
    - ssh_config.hostnames is defined
    - item.ip is defined

- name: "Accept signature"
  ansible.builtin.command: "ssh-keyscan -t ed25519 -H {{ item.ip }} >> {{ ssh_config.known_hosts_path | default(default_known_hosts_path) }}"
  loop: "{{ ssh_config.hostnames }}"
  when:
    - ssh_config is defined
    - ssh_config.hostnames is defined
    - item.ip is defined