---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  timeout: 10m
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">= 91.4.1 < 92.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1440m
  values:
    crds:
      upgradeJob:
        enabled: true

    grafana:
      operator:
        ## Enable references to ConfigMaps containing dashboards in GrafanaDashboard CRs
        ## Set to true to allow dashboards to be loaded from ConfigMap references
        dashboardsConfigMapRefEnabled: true
      defaultDashboardsTimezone: ${timezone}
      ## Configure additional grafana datasources (passed through tpl)
      ## ref: https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
      additionalDataSources: []
      # - name: prometheus-sample
      #   access: proxy
      #   basicAuth: true
      #   secureJsonData:
      #       basicAuthPassword: pass
      #   basicAuthUser: daco
      #   editable: false
      #   jsonData:
      #       tlsSkipVerify: true
      #   orgId: 1
      #   type: prometheus
      #   url: https://{{ printf "%s-prometheus.svc" .Release.Name }}:9090
      #   version: 1
      persistence:
        enabled: true
        type: sts
        storageClassName: rook-ceph-retain
        accessModes:
          - ReadWriteOnce
        size: 10Gi
      admin:
        ## Name of the secret. Can be templated.
        existingSecret: ""
        userKey: admin-user
        passwordKey: admin-password

    kubeControllerManager:
      enabled: true
      service:
        selector:
          k8s-app: kube-controller-manager

    kubeEtcd:
      enabled: true
      service:
        selector:
          # Fix selector for kube-etcd for Talos
          # (set itentionally to kube-controller-manager because all master nodes has the same roles)
          k8s-app: kube-controller-manager
      serviceMonitor:
        enabled: true
        # Add nodename label
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            separator: ;
            regex: ^(.*)$
            targetLabel: nodename
            replacement: $1
            action: replace
        # Remove pod label
        metricRelabelings:
          - action: labeldrop
            regex: pod

    kubeScheduler:
      enabled: true
      service:
        selector:
          k8s-app: kube-controller-manager

    kubeProxy:
      enabled: false

    prometheusOperator:
      admissionWebhooks:
        certManager:
          enabled: true

    prometheus:
      prometheusSpec:
        replicas: 2
        podAntiAffinity: "hard"
        ## If true, a nil or {} value for prometheus.prometheusSpec.serviceMonitorSelector will cause the
        ## prometheus resource to be created with selectors based on values in the helm deployment,
        ## which will also match the servicemonitors created
        ##
        serviceMonitorSelectorNilUsesHelmValues: false

        ## ServiceMonitors to be selected for target discovery.
        ## If {}, select all ServiceMonitors
        ##
        serviceMonitorSelector: {}
        ## Example which selects ServiceMonitors with label "prometheus" set to "somelabel"
        # serviceMonitorSelector:
        #   matchLabels:
        #     prometheus: somelabel

        ## Namespaces to be selected for ServiceMonitor discovery.
        ##
        serviceMonitorNamespaceSelector: {}
        ## Example which selects ServiceMonitors in namespaces with label "prometheus" set to "somelabel"
        # serviceMonitorNamespaceSelector:
        #   matchLabels:
        #     prometheus: somelabel

        ## If true, a nil or {} value for prometheus.prometheusSpec.podMonitorSelector will cause the
        ## prometheus resource to be created with selectors based on values in the helm deployment,
        ## which will also match the podmonitors created
        ##
        podMonitorSelectorNilUsesHelmValues: false

        ## PodMonitors to be selected for target discovery.
        ## If {}, select all PodMonitors
        ##
        podMonitorSelector: {}
        ## Example which selects PodMonitors with label "prometheus" set to "somelabel"
        # podMonitorSelector:
        #   matchLabels:
        #     prometheus: somelabel

        ## If nil, select own namespace. Namespaces to be selected for PodMonitor discovery.
        podMonitorNamespaceSelector: {}
        ## Example which selects PodMonitor in namespaces with label "prometheus" set to "somelabel"
        # podMonitorNamespaceSelector:
        #   matchLabels:
        #     prometheus: somelabel
        additionalScrapeConfigs:
          # cilium
          # - job_name: 'kubernetes-pods'
          #   kubernetes_sd_configs:
          #     - role: pod
          #   relabel_configs:
          #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          #       action: keep
          #       regex: true
          #     - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          #       action: replace
          #       regex: ([^:]+)(?::\d+)?;(\d+)
          #       replacement: $${1}:$${2}
          #       target_label: __address__
          # # cilium hubble
          # - job_name: 'kubernetes-endpoints'
          #   scrape_interval: 30s
          #   kubernetes_sd_configs:
          #     - role: endpoints
          #   relabel_configs:
          #     - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          #       action: keep
          #       regex: true
          #     - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          #       action: replace
          #       target_label: __address__
          #       regex: (.+)(?::\d+);(\d+)
          #       replacement: $$1:$$2
          # cnpg clusters
          - job_name: 'cloudnativepg'
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_label_cnpg_io_cluster]
                action: keep
                regex: .+
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: metrics
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_label_cnpg_io_cluster]
                target_label: cluster
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
