###################################################
# Don not upgrade unless talos' kernel is at >= 7 #
###################################################
# see: https://rook.github.io/docs/rook/v1.20/Storage-Configuration/Advanced/cephx-key-rotation/
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 1440m
  url: https://charts.rook.io/release
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ceph-csi-operator
  namespace: flux-system
spec:
  interval: 1440m
  url: https://ceph.github.io/ceph-csi-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 1440m
  install:
    createNamespace: true
  chart:
    spec:
      chart: rook-ceph
      # version: ">=1.20.7 <1.21.0"
      version: 1.20.7
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
      interval: 15m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
  namespace: rook-ceph
spec:
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  interval: 5m
  chart:
    spec:
      chart: ceph-csi-drivers
      version: ">=1.0.5 <1.1.0"
      sourceRef:
        kind: HelmRepository
        name: ceph-csi-operator
        namespace: flux-system
      interval: 1440m
  values:
    operatorConfig:
      namespace: rook-ceph
      driverSpecDefaults:
        imageSet:
          name: rook-csi-operator-image-set-configmap
        nodePlugin:
          priorityClassName: system-node-critical
        controllerPlugin:
          priorityClassName: system-cluster-critical

    drivers:
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        snapshotPolicy: volumeSnapshot
      cephfs:
        enabled: true
        name: rook-ceph.cephfs.csi.ceph.com
      nfs:
        enabled: false
        name: rook-ceph.nfs.csi.ceph.com
      nvmeof:
        enabled: false
        name: rook-ceph.nvmeof.csi.ceph.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
    - name: ceph-csi-drivers
      namespace: rook-ceph
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      # version: ">=1.20.7 <1.21.0"
      version: 1.20.7
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
      interval: 1440m
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    cephClusterSpec:
      dashboard:
        enabled: true
      storage:
        useAllNodes: true
        useAllDevices: true
      security:
        cephx:
          allowedCiphers:
            - aes
            # - aes256k
          daemon:
            # keyType: aes256k
            keyType: aes
            keyGeneration: 1
            keyRotationPolicy: KeyGeneration
          csi:
            # keyType: aes256k
            keyType: aes # required when Kubernetes nodes don't run Linux kernel 7.0+
            keyGeneration: 1
            keyRotationPolicy: KeyGeneration
          rbdMirrorPeer:
            # keyType: aes256k
            keyType: aes
            keyGeneration: 1
            keyRotationPolicy: KeyGeneration
      network:
        ipFamily: IPv6
        dualStack: true
        connections:
          encryption:
            enabled: true
          compression:
            enabled: true
          requireMsgr2: true
      healthCheck:
        muteHealthWarning:
          AUTH_INSECURE_ROTATING_SERVICE_KEY_TYPE:
            policy: mute
          AUTH_INSECURE_CLIENT_KEY_TYPE:
            policy: mute
          AUTH_INSECURE_KEYS_ALLOWED:
            policy: mute
          AUTH_INSECURE_KEYS_CREATABLE:
            policy: mute
          AUTH_INSECURE_SERVICE_KEY_TYPE:
            policy: mute
          AUTH_INSECURE_SERVICE_TICKETS:
            policy: mute
          AUTH_EMERGENCY_CIPHERS_SET:
            policy: mute
    cephBlockPools:
      - name: rook-ceph-retain
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: rook-ceph-retain
          isDefault: false
          reclaimPolicy: Retain
          allowVolumeExpansion: true
          # see: https://desipient.com/blog/rook-csi-provisioner-empty-secret/
          parameters:
            imageFormat: "2"

            # RBD image features
            # Available for imageFormat: "2". Older releases of CSI RBD
            # support only the `layering` feature. The Linux kernel (KRBD) supports the
            # full complement of features as of 5.4
            # `layering` alone corresponds to Ceph's bitfield value of "2" ;
            # `layering` + `fast-diff` + `object-map` + `deep-flatten` + `exclusive-lock` together
            # correspond to Ceph's OR'd bitfield value of "63". Here we use
            # a symbolic, comma-separated format:
            # For 5.4 or later kernels:
            imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
            # For 5.3 or earlier kernels:
            # imageFeatures: layering

            # The secrets contain Ceph admin credentials.
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-publish-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-publish-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

            # Specify the filesystem type of the volume. If not specified, csi-provisioner
            # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
            # in hyperconverged settings where the volume is mounted on the same node as the osds.
            csi.storage.k8s.io/fstype: ext4
      - name: rook-ceph-delete
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: rook-ceph-delete
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          # see: https://desipient.com/blog/rook-csi-provisioner-empty-secret/
          parameters:
            imageFormat: "2"

            # RBD image features
            # Available for imageFormat: "2". Older releases of CSI RBD
            # support only the `layering` feature. The Linux kernel (KRBD) supports the
            # full complement of features as of 5.4
            # `layering` alone corresponds to Ceph's bitfield value of "2" ;
            # `layering` + `fast-diff` + `object-map` + `deep-flatten` + `exclusive-lock` together
            # correspond to Ceph's OR'd bitfield value of "63". Here we use
            # a symbolic, comma-separated format:
            # For 5.4 or later kernels:
            imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
            # For 5.3 or earlier kernels:
            # imageFeatures: layering

            # The secrets contain Ceph admin credentials.
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-publish-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-publish-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

            # Specify the filesystem type of the volume. If not specified, csi-provisioner
            # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
            # in hyperconverged settings where the volume is mounted on the same node as the osds.
            csi.storage.k8s.io/fstype: ext4

    cephFileSystems: []
    cephObjectStores: []

    # -- Settings for the filesystem snapshot class
    # @default -- See [CephFS Snapshots](../Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md#cephfs-snapshots)
    # cephFileSystemVolumeSnapshotClass:
    #   enabled: false
    #   name: ceph-filesystem
    #   isDefault: true
    #   deletionPolicy: Delete
    #   annotations: {}
    #   labels: {}
    #   # see https://rook.io/docs/rook/v1.10/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot/#cephfs-snapshots for available configuration
    #   parameters: {}

    # -- Settings for the block pool snapshot class
    # @default -- See [RBD Snapshots](../Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md#rbd-snapshots)
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: ceph-block
      isDefault: true
      deletionPolicy: Delete
      annotations: {}
      labels:
        velero.io/csi-volumesnapshot-class: "true"
      # see https://rook.io/docs/rook/v1.10/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot/#rbd-snapshots for available configuration
      parameters: {}
