server:
  ingress:
    enabled: true
    hosts:
      - host: "{{ k3s.config.vault.server.ingress.host }}"
        paths:
          - /
{% if k3s.config.vault.storage.type == "storageClass" %}
  dataStorage:
    enabled: true
    size: "{{ k3s.config.vault.storage.size | default('10Gi') }}"
    storageClass: {{ k3s.config.vault.storage.storageClass | default("null") }}
{% endif %}
  ha:
    enabled: true
    replicas: {{ k3s.config.vault.server.ha.replicas }}
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address     = "0.0.0.0:8200"
      }

      service_registration "kubernetes" {
        namespace      = "default"
        pod_name       = "vault"
      }
{% if k3s.config.vault.storage.type == "postgresql" %}

      storage "postgresql" {
        connection_url = "postgres://{{ k3s.config.vault.storage.username }}:{{ k3s.config.vault.storage.password }}@{{ k3s.config.vault.storage.address }}:{{ k3s.config.vault.storage.port | default(5432) }}/{{ k3s.config.vault.storage.database_name | default('vault') }}?sslmode={{ k3s.config.vault.storage.ssl_mode | default('verify-full') }}"
        ha_enabled = true
      }
{% endif %}
{% if k3s.config.vault.storage.type == "consul" %}

      storage "consul" {
        address = "consul-server.consul:8500"
        path    = "vault"
      }
{% endif %}

ui:
  enabled: true
  serviceType: "ClusterIP"
  publishNotReadyAddresses: false
  activeVaultPodOnly: true